#pragma warning disable IDE0060, IDE0059, SA1313
namespace AmazonLambdaExtension.Generator;

using AmazonLambdaExtension.Generator.Models;

using SourceGenerateHelper;

internal static class LambdaSourceBuilder
{
    private const string V2RequestType = "global::Amazon.Lambda.APIGatewayEvents.APIGatewayHttpApiV2ProxyRequest";
    private const string V2AuthorizerRequestType = "global::Amazon.Lambda.APIGatewayEvents.APIGatewayCustomAuthorizerV2Request";
    private const string V2ResponseType = "global::Amazon.Lambda.APIGatewayEvents.APIGatewayHttpApiV2ProxyResponse";
    private const string LambdaContextType = "global::Amazon.Lambda.Core.ILambdaContext";
    private const string InvocationContextType = "global::AmazonLambdaExtension.Filters.LambdaInvocationContext";
    private const string FilterDelegateType = "global::AmazonLambdaExtension.Filters.LambdaFilterDelegate";
    private const string HttpResultType = "global::AmazonLambdaExtension.APIGateway.IHttpResult";
    private const string HttpResultsType = "global::AmazonLambdaExtension.APIGateway.HttpResults";
    private const string AuthorizerResultType = "global::AmazonLambdaExtension.APIGateway.IAuthorizerResult";
    private const string AuthorizerResultsType = "global::AmazonLambdaExtension.APIGateway.AuthorizerResults";
    private const string AuthorizerSimpleResponseType = "global::Amazon.Lambda.APIGatewayEvents.APIGatewayCustomAuthorizerV2SimpleResponse";
    private const string AuthorizerIamResponseType = "global::Amazon.Lambda.APIGatewayEvents.APIGatewayCustomAuthorizerV2IamResponse";
    private const string StringConverterType = "global::AmazonLambdaExtension.Binders.StringConverter";
    private const string BodySerializerType = "global::AmazonLambdaExtension.Serialization.IBodySerializer";
    private const string DefaultBodySerializerType = "global::AmazonLambdaExtension.Serialization.JsonBodySerializer";
    private const string RequestValidatorType = "global::AmazonLambdaExtension.Validation.IRequestValidator";
    private const string DefaultRequestValidatorType = "global::AmazonLambdaExtension.Validation.DataAnnotationsRequestValidator";
    private const string ApiExceptionType = "global::AmazonLambdaExtension.ApiException";
    private const string GetRequiredService = "global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService";
    private const string GetRequiredKeyedService = "global::Microsoft.Extensions.DependencyInjection.ServiceProviderKeyedServiceExtensions.GetRequiredKeyedService";
    private const string BuildServiceProvider = "global::Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider";
    private const string CreateAsyncScope = "global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.CreateAsyncScope";
    private const string ServiceProviderOptionsType = "global::Microsoft.Extensions.DependencyInjection.ServiceProviderOptions";

    public static void BuildShared(SourceBuilder builder, LambdaModel model)
    {
        // 全ハンドラー共通の静的フィールド(ターゲット・シリアライザー等)を含む partial クラスを生成
        // Generate the partial class containing static fields shared across all handlers
        builder.AutoGenerated();
        builder.EnableNullable();
        builder.NewLine();

        if (!String.IsNullOrEmpty(model.Namespace))
        {
            builder.Namespace(model.Namespace);
            builder.NewLine();
        }

        builder.AppendLine($"partial class {model.ClassName}");
        builder.BeginBlock();

        BuildStaticFields(builder, model);

        builder.EndBlock();
    }

    public static void Build(SourceBuilder builder, LambdaModel model, HandlerModel handler)
    {
        // 指定ハンドラー向けのラッパーメソッドを含む partial クラスを生成
        // Generate the partial class with the wrapper method for the specified handler
        builder.AutoGenerated();
        builder.EnableNullable();
        builder.NewLine();

        if (!String.IsNullOrEmpty(model.Namespace))
        {
            builder.Namespace(model.Namespace);
            builder.NewLine();
        }

        builder.AppendLine($"partial class {model.ClassName}");
        builder.BeginBlock();

        if (model.Filters.Count > 0)
        {
            BuildInnerMethod(builder, handler);
            builder.NewLine();
        }

        BuildHandlerMethod(builder, model, handler);

        builder.EndBlock();
    }

    private static void BuildStaticFields(SourceBuilder builder, LambdaModel model)
    {
        // ハンドラーの使用状況を事前チェックして必要なフィールドの要否を判定
        // Pre-check handler usage to determine which static fields are required
        var handlers = model.Handlers;
        var hasHttpHandler = handlers.Any(static h =>
            (h.Type == HandlerType.HttpApi) ||
            (h.Type == HandlerType.FunctionUrl) ||
            (h.Type == HandlerType.HttpApiAuthorizer));
        var hasBodyParam = handlers.Any(static h =>
            h.Parameters.Any(static p => p.BindingType == ParameterBindingType.FromBody));
        var hasValidation = handlers.Any(static h =>
            h.Parameters.Any(static p => (p.BindingType == ParameterBindingType.FromBody) && !p.SkipValidation));

        if (model.ServiceResolver is not null)
        {
            // DIコンテナを構築（Debug ビルドのみ scope 検証を有効化）し、コンストラクタ DI でターゲットを生成
            // Build DI container (scope validation only in Debug builds) and create target via constructor injection
            builder.AppendLine("private static readonly global::System.IServiceProvider __provider__ = BuildProvider();");
            builder.NewLine();
            builder.AppendLine("private static global::System.IServiceProvider BuildProvider()");
            builder.BeginBlock();
            builder.AppendLine($"var services = {model.ServiceResolver.FullName}.ConfigureServices();");
            builder.AppendLine($"return {BuildServiceProvider}(services, new {ServiceProviderOptionsType}");
            builder.BeginBlock();
            builder.AppendLine("#if DEBUG");
            builder.AppendLine("ValidateScopes = true,");
            builder.AppendLine("#endif");
            builder.EndBlock(semicolon: false);
            builder.AppendLine(");");
            builder.EndBlock();
            builder.NewLine();

            // target（本体は singleton。コンストラクタ引数のみ DI から解決＝Controller 的な特別扱い）
            // target (singleton; only constructor arguments come from DI, like ASP.NET Core controllers)
            var ctorArgs = String.Join(", ", model.ConstructorParameters.Select(static (p, _) => $"{GetRequiredService}<{p.FullName}>(__provider__)"));
            builder.AppendLine($"private static readonly {model.FunctionType.FullName} __target__ = new {model.FunctionType.FullName}({ctorArgs});");
        }
        else
        {
            // DIなしでデフォルトコンストラクタでターゲットインスタンスを生成
            // Create target instance with default constructor (no DI)
            builder.AppendLine($"private static readonly {model.FunctionType.FullName} __target__ = new {model.FunctionType.FullName}();");
        }

        if (hasHttpHandler)
        {
            builder.NewLine();
            if (model.ServiceResolver is not null)
            {
                // DIから ILambdaSerializer を解決
                // Resolve ILambdaSerializer from DI container
                builder.AppendLine("private static readonly global::Amazon.Lambda.Core.ILambdaSerializer __lambdaSerializer__ =");
                builder.AppendLine($"    {GetRequiredService}<global::Amazon.Lambda.Core.ILambdaSerializer>(__provider__);");
            }
            else
            {
                // DIなしの場合はデフォルトの JSON シリアライザーを使用
                // Use default JSON serializer when no DI is configured
                builder.AppendLine("private static readonly global::Amazon.Lambda.Core.ILambdaSerializer __lambdaSerializer__ =");
                builder.AppendLine("    new global::Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer();");
            }
        }

        if (hasBodyParam && model.ServiceResolver is not null)
        {
            // DIから IBodySerializer を解決
            // Resolve IBodySerializer from DI container
            builder.NewLine();
            builder.AppendLine($"private static readonly {BodySerializerType} __bodySerializer__ =");
            builder.AppendLine($"    {GetRequiredService}<{BodySerializerType}>(__provider__);");
        }
        else if (hasBodyParam)
        {
            builder.NewLine();
            builder.AppendLine($"private static readonly {BodySerializerType} __bodySerializer__ =");
            builder.AppendLine($"    {DefaultBodySerializerType}.Default;");
        }

        if (hasValidation && model.ServiceResolver is not null)
        {
            // DIからリクエストバリデーターを解決
            // Resolve IRequestValidator from DI container
            builder.NewLine();
            builder.AppendLine($"private static readonly {RequestValidatorType} __requestValidator__ =");
            builder.AppendLine($"    {GetRequiredService}<{RequestValidatorType}>(__provider__);");
        }
        else if (hasValidation)
        {
            builder.NewLine();
            builder.AppendLine($"private static readonly {RequestValidatorType} __requestValidator__ =");
            builder.AppendLine($"    new {DefaultRequestValidatorType}();");
        }
    }

    private static void BuildInnerMethod(SourceBuilder builder, HandlerModel handler)
    {
        // フィルターパイプラインの最内部処理となる __Inner__ メソッドを生成
        // Generate the __Inner__ method that is the innermost delegate of the filter pipeline
        var methodName = handler.MethodName;
        builder.AppendLine($"private static async global::System.Threading.Tasks.ValueTask __{methodName}_Inner__(");
        builder.AppendLine($"    {InvocationContextType} ctx)");
        builder.BeginBlock();

        if (handler.Type != HandlerType.Event)
        {
            // HTTPリクエストをコンテキストから取り出してローカル変数に割り当て
            // Extract HTTP request from context and assign to local variable
            builder.AppendLine($"var request = ({GetEntryRequestType(handler)})ctx.Request;");
            builder.NewLine();
        }
        else
        {
            // Get event type
            var eventParam = handler.GetRequestParam();
            if (eventParam is not null)
            {
                builder.AppendLine($"var ev = ({eventParam.Type.FullName})ctx.Request;");
                builder.NewLine();
            }
        }

        BuildParameterBindings(builder, handler, hasFilter: true);

        BuildHandlerInvocation(builder, handler, hasFilter: true);

        builder.EndBlock();
    }

    private static bool UsesScope(LambdaModel model, HandlerModel handler)
    {
        // DI 利用時で、フィルターか [FromServices] がある場合のみ invocation scope が必要
        // A per-invocation scope is needed only with DI when filters or [FromServices] are present
        return model.ServiceResolver is not null &&
            (model.Filters.Count > 0 ||
             handler.Parameters.Any(static p => p.BindingType == ParameterBindingType.FromServices));
    }

    private static void BuildInlinePipeline(SourceBuilder builder, LambdaModel model, HandlerModel handler)
    {
        // フィルターを invocation ごとに解決し、逆順にラップしてパイプラインデリゲートをローカルに構築
        // Resolve filters per invocation and build the pipeline delegate locally by wrapping in reverse order
        var methodName = handler.MethodName;
        var filters = model.Filters;

        // 最内部デリゲートから始めて外側に向かってフィルターを順次ラップ（解決と連結を同一ループで実施）
        // Start from the innermost delegate and wrap each filter outward (resolve and chain in one loop)
        builder.AppendLine($"{FilterDelegateType} __pipeline__ = __{methodName}_Inner__;");
        for (var i = filters.Count - 1; i >= 0; i--)
        {
            var filterType = filters[i].FullName;
            builder.AppendLine(model.ServiceResolver is not null
                // DIから（scope 経由で）フィルターインスタンスを解決
                // Resolve filter instance from DI (via the scope)
                ? $"var __filter{i}__ = {GetRequiredService}<{filterType}>(__sp__);"
                // DIなしの場合はデフォルトコンストラクタでフィルターインスタンスを生成
                // Instantiate filter with default constructor (no DI)
                : $"var __filter{i}__ = new {filterType}();");

            builder.AppendLine($"var __chain{i}__ = __pipeline__;");
            builder.AppendLine($"__pipeline__ = c => __filter{i}__.InvokeAsync(c, __chain{i}__);");
        }
    }

    private static void BuildHandlerMethod(SourceBuilder builder, LambdaModel model, HandlerModel handler)
    {
        // Lambda エントリポイントとなる public static メソッド (*_Handler) を生成
        // Generate the public static *_Handler method that serves as the Lambda entry point
        var methodName = handler.MethodName;
        var filters = model.Filters;
        var hasFilters = filters.Count > 0;

        // ハンドラー種別と戻り値型に応じた戻り値型文字列を決定
        // Determine the return type string based on handler kind and result type
        string returnType;
        if (handler.Type == HandlerType.HttpApiAuthorizer)
        {
            returnType = $"global::System.Threading.Tasks.Task<{AuthorizerResponseType(handler)}>";
        }
        else if ((handler.Type == HandlerType.HttpApi) || (handler.Type == HandlerType.FunctionUrl))
        {
            returnType = $"global::System.Threading.Tasks.Task<{V2ResponseType}>";
        }
        else
        {
            returnType = handler.ResultType is not null ?
                $"global::System.Threading.Tasks.Task<{handler.ResultType.FullName}>"
                : "global::System.Threading.Tasks.Task";
        }

        builder.AppendLine($"public static async {returnType} {methodName}_Handler(");

        if (handler.Type == HandlerType.Event)
        {
            // Determine request param type
            var requestParam = handler.GetRequestParam();
            var reqTypeName = requestParam?.Type.FullName ?? V2RequestType;
            builder.AppendLine($"    {reqTypeName} ev,");
            builder.AppendLine($"    {LambdaContextType} context)");
        }
        else
        {
            builder.AppendLine($"    {GetEntryRequestType(handler)} request,");
            builder.AppendLine($"    {LambdaContextType} context)");
        }

        builder.BeginBlock();

        if (UsesScope(model, handler))
        {
            // invocation ごとに DI scope を作成（Scoped/Transient 依存をこの単位で解決し、終了時に破棄）
            // Create a DI scope per invocation (scoped/transient dependencies resolve here and dispose at the end)
            builder.AppendLine($"await using var __scope__ = {CreateAsyncScope}(__provider__);");
            builder.AppendLine("var __sp__ = __scope__.ServiceProvider;");
            builder.NewLine();
        }

        if (hasFilters)
        {
            // フィルターあり: InvocationContext を作成しパイプラインを実行、結果を抽出
            // With filters: create InvocationContext, execute pipeline, then extract result
            builder.AppendLine($"var ctx = new {InvocationContextType}");
            builder.BeginBlock();

            builder.AppendLine(handler.Type == HandlerType.Event ? "Request = ev," : "Request = request,");

            builder.AppendLine("LambdaContext = context,");
            builder.AppendLine("CancellationToken = default,");
            if (model.ServiceResolver is not null)
            {
                builder.AppendLine("ServiceProvider = __sp__,");
            }
            builder.EndBlock(semicolon: true);
            builder.NewLine();

            BuildInlinePipeline(builder, model, handler);
            builder.NewLine();

            BuildTryCatchWithFilter(builder, handler);
        }
        else
        {
            // フィルターなし: パラメーターバインディングとハンドラー呼び出しを直接実行
            // Without filters: directly execute parameter binding and handler invocation
            if (handler.Type == HandlerType.Event)
            {
                BuildEventTryCatch(builder, handler);
            }
            else
            {
                BuildHttpTryCatch(builder, handler);
            }
        }

        builder.EndBlock();
    }

    private static void BuildTryCatchWithFilter(SourceBuilder builder, HandlerModel handler)
    {
        builder.AppendLine("try");
        builder.BeginBlock();
        builder.AppendLine("await __pipeline__(ctx);");
        builder.EndBlock();

        if (handler.Type == HandlerType.HttpApiAuthorizer)
        {
            builder.AppendLine("catch (global::System.Exception ex)");
            builder.BeginBlock();
            builder.AppendLine("context.Logger.LogLine(ex.ToString());");
            builder.AppendLine($"return {AuthorizerResponseCall(handler, $"{AuthorizerResultsType}.Deny()", hasFilter: true)};");
            builder.EndBlock();
        }
        else if ((handler.Type == HandlerType.HttpApi) || (handler.Type == HandlerType.FunctionUrl))
        {
            builder.AppendLine($"catch ({ApiExceptionType} ex)");
            builder.BeginBlock();
            if (handler.ResponseType == ResponseType.HttpResult)
            {
                builder.AppendLine($"return {ToResponseCall($"{HttpResultsType}.NewResult((global::System.Net.HttpStatusCode)ex.StatusCode, ex.Message)")};");
            }
            else
            {
                builder.AppendLine($"return new {V2ResponseType} {{ StatusCode = (int)ex.StatusCode, Body = ex.Message }};");
            }
            builder.EndBlock();

            builder.AppendLine("catch (global::System.Exception ex)");
            builder.BeginBlock();
            builder.AppendLine("context.Logger.LogLine(ex.ToString());");
            if (handler.ResponseType == ResponseType.HttpResult)
            {
                builder.AppendLine($"return {ToResponseCall($"{HttpResultsType}.InternalServerError()")};");
            }
            else
            {
                builder.AppendLine($"return new {V2ResponseType} {{ StatusCode = 500 }};");
            }
            builder.EndBlock();
        }
        else
        {
            builder.AppendLine("catch (global::System.Exception ex)");
            builder.BeginBlock();
            builder.AppendLine("context.Logger.LogLine(ex.ToString());");
            builder.AppendLine("throw;");
            builder.EndBlock();
        }

        builder.NewLine();
        BuildResultExtraction(builder, handler, hasFilter: true);
    }

    private static void BuildHttpTryCatch(SourceBuilder builder, HandlerModel handler)
    {
        builder.AppendLine("try");
        builder.BeginBlock();

        BuildParameterBindings(builder, handler, hasFilter: false);
        BuildHandlerInvocation(builder, handler, hasFilter: false);

        builder.EndBlock();

        if (handler.Type == HandlerType.HttpApiAuthorizer)
        {
            builder.AppendLine("catch (global::System.Exception ex)");
            builder.BeginBlock();
            builder.AppendLine("context.Logger.LogLine(ex.ToString());");
            builder.AppendLine($"return {AuthorizerResponseCall(handler, $"{AuthorizerResultsType}.Deny()", hasFilter: false)};");
            builder.EndBlock();
        }
        else
        {
            builder.AppendLine($"catch ({ApiExceptionType} ex)");
            builder.BeginBlock();
            if (handler.ResponseType == ResponseType.HttpResult)
            {
                builder.AppendLine($"return {ToResponseCall($"{HttpResultsType}.NewResult((global::System.Net.HttpStatusCode)ex.StatusCode, ex.Message)")};");
            }
            else
            {
                builder.AppendLine($"return new {V2ResponseType} {{ StatusCode = (int)ex.StatusCode, Body = ex.Message }};");
            }
            builder.EndBlock();

            builder.AppendLine("catch (global::System.Exception ex)");
            builder.BeginBlock();
            builder.AppendLine("context.Logger.LogLine(ex.ToString());");
            if (handler.ResponseType == ResponseType.HttpResult)
            {
                builder.AppendLine($"return {ToResponseCall($"{HttpResultsType}.InternalServerError()")};");
            }
            else
            {
                builder.AppendLine($"return new {V2ResponseType} {{ StatusCode = 500 }};");
            }
            builder.EndBlock();
        }
    }

    private static void BuildEventTryCatch(SourceBuilder builder, HandlerModel handler)
    {
        builder.AppendLine("try");
        builder.BeginBlock();

        BuildParameterBindings(builder, handler, hasFilter: false);
        BuildHandlerInvocation(builder, handler, hasFilter: false);

        builder.EndBlock();
        builder.AppendLine("catch (global::System.Exception ex)");
        builder.BeginBlock();
        builder.AppendLine("context.Logger.LogLine(ex.ToString());");
        builder.AppendLine("throw;");
        builder.EndBlock();
    }

    private static void BuildParameterBindings(SourceBuilder builder, HandlerModel handler, bool hasFilter)
    {
        // 全パラメーターを順にバインディングコードを生成
        // Generate binding code for each parameter in order
        var parameters = handler.Parameters;
        for (var i = 0; i < parameters.Count; i++)
        {
            var p = parameters[i];
            BuildParameterBinding(builder, handler, p, i, hasFilter);
        }
    }

    private static void BuildParameterBinding(SourceBuilder builder, HandlerModel handler, ParameterModel param, int index, bool hasFilter)
    {
        var pVar = $"p{index}";
        var pRaw = $"p{index}raw";
        var requestVar = handler.Type == HandlerType.Event ? "ev" : "request";
        var typeName = param.Type.FullName;
        var key = param.Key;

        string BadRequest400(string paramName)
        {
            if (handler.ResponseType == ResponseType.HttpResult)
            {
                return $"return {ToResponseCall($"{HttpResultsType}.BadRequest($\"Invalid parameter: {paramName}\")")};";
            }
            return $"return new {V2ResponseType} {{ StatusCode = 400, " +
                   $"Body = $\"Invalid parameter: {paramName}\" }};";
        }

        string BadRequestBody(string message)
        {
            if (handler.ResponseType == ResponseType.HttpResult)
            {
                return $"return {ToResponseCall($"{HttpResultsType}.BadRequest(\"{message}\")")};";
            }
            return $"return new {V2ResponseType} {{ StatusCode = 400, Body = \"{message}\" }};";
        }

        switch (param.BindingType)
        {
            case ParameterBindingType.Request:
                // request/ev 変数はメソッド引数にそのまま存在するため何も不要
                // already in scope as 'request'
                return;

            case ParameterBindingType.Context:
                // context 変数はメソッド引数にそのまま存在するため何も不要
                // already in scope as 'context'
                return;

            case ParameterBindingType.FromServices:
                // invocation scope からサービスを解決（フィルター内は ctx.ServiceProvider 経由）
                // キー指定時は keyed service として解決する
                // Resolve service from the invocation scope (via ctx.ServiceProvider inside filters)
                // Resolve as a keyed service when a key is specified
                {
                    var serviceProvider = hasFilter ? "ctx.ServiceProvider" : "__sp__";
                    builder.AppendLine(String.IsNullOrEmpty(param.Key)
                        ? $"var {pVar} = {GetRequiredService}<{typeName}>({serviceProvider});"
                        : $"var {pVar} = {GetRequiredKeyedService}<{typeName}>({serviceProvider}, \"{param.Key}\");");
                }

                builder.NewLine();
                return;

            case ParameterBindingType.FromBody:
                // リクエストボディをデシリアライズし、バリデーションを実行
                // Deserialize request body and run validation unless skipped
                builder.AppendLine($"var {pVar} = default({typeName})!;");
                builder.AppendLine("try");
                builder.BeginBlock();
                builder.AppendLine($"{pVar} = __bodySerializer__.Deserialize<{typeName}>({requestVar}.Body ?? string.Empty);");
                builder.EndBlock();
                builder.AppendLine("catch (global::System.Text.Json.JsonException)");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = {HttpResultsType}.BadRequest(\"Invalid request body.\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine(BadRequestBody("Invalid request body."));
                }
                builder.EndBlock();

                // null 非許容（NRT 注釈なし・非 Nullable）のボディは必須として 400 を返す
                // Treat a non-nullable body (no NRT annotation / not Nullable) as required and return 400
                if (!param.IsNullableBodyParameter())
                {
                    builder.AppendLine($"if ({pVar} is null)");
                    builder.BeginBlock();
                    if (hasFilter)
                    {
                        builder.AppendLine($"ctx.Result = {HttpResultsType}.BadRequest(\"Request body is required.\");");
                        builder.AppendLine("return;");
                    }
                    else
                    {
                        builder.AppendLine(BadRequestBody("Request body is required."));
                    }
                    builder.EndBlock();
                }

                if (!param.SkipValidation)
                {
                    builder.AppendLine($"if ({pVar} is not null && !__requestValidator__.Validate({pVar}))");
                    builder.BeginBlock();
                    if (hasFilter)
                    {
                        builder.AppendLine($"ctx.Result = {HttpResultsType}.BadRequest(\"Validation failed: {param.Name}\");");
                        builder.AppendLine("return;");
                    }
                    else
                    {
                        builder.AppendLine($"{BadRequest400(param.Name)}");
                    }
                    builder.EndBlock();
                }
                builder.NewLine();
                return;

            case ParameterBindingType.FromAuthorizer:
                // Lambda オーソライザーが付与したカスタムコンテキストから値を取り出して変換
                // Extract and convert value from custom authorizer context injected by Lambda authorizer
                builder.AppendLine($"var {pVar} = default({typeName});");
                builder.AppendLine($"if ({requestVar}.RequestContext?.Authorizer?.Lambda is not null &&");
                builder.AppendLine($"    {requestVar}.RequestContext.Authorizer.Lambda.TryGetValue(\"{key}\", out var {pRaw}ca) &&");
                builder.AppendLine($"    {pRaw}ca is not null)");
                builder.BeginBlock();
                if (String.IsNullOrEmpty(param.ConverterMethod))
                {
                    builder.AppendLine($"{pVar} = {pRaw}ca as {typeName};");
                }
                else
                {
                    var isEnum = param.ConverterMethod == "TryToEnum";
                    var converterCall = isEnum
                        ? $"{StringConverterType}.TryToEnum<{param.Type.GetBaseTypeName()}>(({pRaw}ca as string ?? string.Empty).AsSpan(), out var {pVar}tmp)"
                        : $"{StringConverterType}.{param.ConverterMethod}(({pRaw}ca as string ?? string.Empty).AsSpan(), out var {pVar}tmp)";
                    builder.AppendLine($"if (!{converterCall})");
                    builder.BeginBlock();
                    if (hasFilter)
                    {
                        builder.AppendLine($"ctx.Result = {HttpResultsType}.BadRequest($\"Invalid parameter: {key}\");");
                        builder.AppendLine("return;");
                    }
                    else
                    {
                        builder.AppendLine(BadRequest400(key));
                    }
                    builder.EndBlock();
                    builder.AppendLine($"{pVar} = {pVar}tmp;");
                }
                builder.EndBlock();
                builder.NewLine();
                return;

            case ParameterBindingType.FromRoute:
                // パスパラメーターディクショナリから値を取得して型変換
                // Retrieve and convert value from path parameters dictionary
                BuildScalarOrArrayBinding(
                    builder,
                    handler,
                    param,
                    index,
                    hasFilter,
                    $"{requestVar}.PathParameters");
                return;

            case ParameterBindingType.FromQuery:
                // クエリストリングディクショナリから値を取得して型変換
                // Retrieve and convert value from query string parameters dictionary
                BuildScalarOrArrayBinding(
                    builder,
                    handler,
                    param,
                    index,
                    hasFilter,
                    $"{requestVar}.QueryStringParameters");
                return;

            case ParameterBindingType.FromHeader:
                // リクエストヘッダーディクショナリから値を取得して型変換
                // Retrieve and convert value from request headers dictionary
                BuildScalarOrArrayBinding(
                    builder,
                    handler,
                    param,
                    index,
                    hasFilter,
                    $"{requestVar}.Headers");
                return;
        }
    }

    private static void BuildScalarOrArrayBinding(SourceBuilder builder, HandlerModel handler, ParameterModel param, int index, bool hasFilter, string dictExpr)
    {
        // 型に応じて 配列 / Nullable<T> / スカラー のバインディングコードを生成
        // Generate binding code for array, Nullable<T>, or scalar type accordingly
        var pVar = $"p{index}";
        var pRaw = $"p{index}raw";
        var typeName = param.Type.FullName;
        var key = param.Key;
        var defaultLiteral = param.HasDefault ? (param.DefaultValueLiteral ?? "default") : null;

        string Bad400()
        {
            if (handler.ResponseType == ResponseType.HttpResult)
            {
                return $"return {ToResponseCall($"{HttpResultsType}.BadRequest($\"Invalid parameter: {key}\")")};";
            }
            return $"return new {V2ResponseType} {{ StatusCode = 400, Body = $\"Invalid parameter: {key}\" }};";
        }

        if (param.Type.IsArray && param.Type.ElementType is not null)
        {
            // カンマ分割で複数値を配列に変換、各要素を型変換
            // Split comma-separated values into array and convert each element
            var elemType = param.Type.ElementType.FullName;
            var converterMethod = param.ConverterMethod;
            builder.AppendLine($"var {pVar} = global::System.Array.Empty<{elemType}>();");
            builder.AppendLine($"if ({dictExpr} is not null &&");
            builder.AppendLine($"    {dictExpr}.TryGetValue(\"{key}\", out var {pRaw}) &&");
            builder.AppendLine($"    {pRaw} is not null)");
            builder.BeginBlock();
            builder.AppendLine($"var {pVar}parts = {pRaw}.Split(',');");
            builder.AppendLine($"{pVar} = new {elemType}[{pVar}parts.Length];");
            builder.AppendLine($"for (var i = 0; i < {pVar}parts.Length; i++)");
            builder.BeginBlock();
            if (String.IsNullOrEmpty(converterMethod))
            {
                builder.AppendLine($"{pVar}[i] = {pVar}parts[i];");
            }
            else
            {
                var isEnum = converterMethod == "TryToEnum";
                var converterCall = isEnum
                    ? $"!{StringConverterType}.TryToEnum<{elemType}>({pVar}parts[i].AsSpan(), out {pVar}[i])"
                    : $"!{StringConverterType}.{converterMethod}({pVar}parts[i].AsSpan(), out {pVar}[i])";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = {HttpResultsType}.BadRequest($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine(Bad400());
                }
                builder.EndBlock();
            }
            builder.EndBlock();
            builder.EndBlock();
            builder.NewLine();
        }
        else if (param.Type.IsNullable && param.Type.UnderlyingType is not null)
        {
            // Nullable<T>: 値が存在する場合のみ型変換を実施
            // Nullable<T>: perform type conversion only when the value is present
            var baseType = param.Type.UnderlyingType.FullName;
            var converterMethod = param.ConverterMethod;
            var init = defaultLiteral is not null ? $"({typeName}){defaultLiteral}" : $"({typeName})null";
            builder.AppendLine($"var {pVar} = {init};");
            builder.AppendLine($"if ({dictExpr} is not null &&");
            builder.AppendLine($"    {dictExpr}.TryGetValue(\"{key}\", out var {pRaw}) &&");
            builder.AppendLine($"    {pRaw} is not null)");
            builder.BeginBlock();
            if (String.IsNullOrEmpty(converterMethod))
            {
                builder.AppendLine($"{pVar} = {pRaw};");
            }
            else
            {
                var isEnum = converterMethod == "TryToEnum";
                var converterCall = isEnum
                    ? $"!{StringConverterType}.TryToEnum<{baseType}>({pRaw}.AsSpan(), out var {pVar}tmp)"
                    : $"!{StringConverterType}.{converterMethod}({pRaw}.AsSpan(), out var {pVar}tmp)";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = {HttpResultsType}.BadRequest($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine(Bad400());
                }
                builder.EndBlock();
                builder.AppendLine($"{pVar} = {pVar}tmp;");
            }
            builder.EndBlock();
            builder.NewLine();
        }
        else
        {
            // スカラー: string はそのまま取得、その他の型は StringConverter で変換
            // Scalar: take string as-is or convert other types via StringConverter
            var converterMethod = param.ConverterMethod;
            if (String.IsNullOrEmpty(converterMethod))
            {
                // string
                var init = defaultLiteral is not null ? $"({typeName}){defaultLiteral}!" : $"default({typeName})!";
                builder.AppendLine($"var {pVar} = {init};");
                builder.AppendLine($"if ({dictExpr} is not null &&");
                builder.AppendLine($"    {dictExpr}.TryGetValue(\"{key}\", out var {pRaw}))");
                builder.BeginBlock();
                builder.AppendLine($"{pVar} = {pRaw};");
                builder.EndBlock();
                builder.NewLine();
            }
            else
            {
                var init = defaultLiteral is not null ? $"({typeName}){defaultLiteral}" : $"default({typeName})";
                builder.AppendLine($"var {pVar} = {init};");
                builder.AppendLine($"if ({dictExpr} is not null &&");
                builder.AppendLine($"    {dictExpr}.TryGetValue(\"{key}\", out var {pRaw}) &&");
                builder.AppendLine($"    {pRaw} is not null)");
                builder.BeginBlock();
                var isEnum = converterMethod == "TryToEnum";
                var converterCall = isEnum
                    ? $"!{StringConverterType}.TryToEnum<{typeName}>({pRaw}.AsSpan(), out {pVar})"
                    : $"!{StringConverterType}.{converterMethod}({pRaw}.AsSpan(), out {pVar})";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = {HttpResultsType}.BadRequest($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine(Bad400());
                }
                builder.EndBlock();
                builder.EndBlock();
                builder.NewLine();
            }
        }
    }

    private static void BuildHandlerInvocation(SourceBuilder builder, HandlerModel handler, bool hasFilter)
    {
        // 引数リストを組み立ててターゲットメソッドを呼び出し、結果をコンテキストまたは戻り値に設定
        // Build argument list, invoke target method, and assign result to context or return
        var args = BuildCallArgs(handler, hasFilter);
        var awaitPrefix = handler.IsAsync ? "await " : string.Empty;

        if (handler.Type == HandlerType.Event)
        {
            if (handler.ResultType is not null)
            {
                builder.AppendLine($"var __result__ = {awaitPrefix}__target__.{handler.MethodName}({args});");
                builder.AppendLine(hasFilter ? "ctx.Result = __result__;" : "return __result__;");
            }
            else
            {
                builder.AppendLine($"{awaitPrefix}__target__.{handler.MethodName}({args});");
            }

            return;
        }

        builder.AppendLine($"var __result__ = {awaitPrefix}__target__.{handler.MethodName}({args});");

        if (hasFilter)
        {
            builder.AppendLine("ctx.Result = __result__;");
        }
        else
        {
            BuildResultExtraction(builder, handler, hasFilter: false);
        }
    }

    private static void BuildResultExtraction(SourceBuilder builder, HandlerModel handler, bool hasFilter)
    {
        // ハンドラー種別に応じて結果をシリアライズまたは変換して返値を生成
        // Serialize or convert the result according to handler kind and generate the return statement
        if (handler.Type == HandlerType.Event)
        {
            if (handler.ResultType is not null && hasFilter)
            {
                builder.AppendLine($"return ({handler.ResultType.FullName})ctx.Result!;");
            }
        }
        else if (handler.Type == HandlerType.HttpApiAuthorizer)
        {
            if (hasFilter)
            {
                builder.AppendLine($"var result = ({AuthorizerResultType})ctx.Result!;");
                builder.AppendLine($"return {AuthorizerResponseCall(handler, "result", hasFilter: true)};");
            }
            else
            {
                builder.AppendLine($"return {AuthorizerResponseCall(handler, "__result__", hasFilter: false)};");
            }
        }
        else if ((handler.Type == HandlerType.HttpApi) || (handler.Type == HandlerType.FunctionUrl))
        {
            if (handler.ResponseType == ResponseType.HttpResult)
            {
                if (hasFilter)
                {
                    builder.AppendLine($"if (ctx.Result is {HttpResultType} httpResult)");
                    builder.BeginBlock();
                    builder.AppendLine($"return {ToResponseCall("httpResult")};");
                    builder.EndBlock();
                    builder.NewLine();
                    builder.AppendLine($"return {ToResponseCall($"{HttpResultsType}.InternalServerError()")};");
                }
                else
                {
                    builder.AppendLine($"return {ToResponseCall("__result__")};");
                }
            }
            else if (handler.ResponseType == ResponseType.ProxyResponse)
            {
                // APIGatewayHttpApiV2ProxyResponse はそのまま返す
                // Return APIGatewayHttpApiV2ProxyResponse as-is
                builder.AppendLine(hasFilter ? $"return ({V2ResponseType})ctx.Result!;" : "return __result__;");
            }
            else
            {
                // その他の戻り値は HttpResults.Ok(...) 相当で 200 応答に包む
                // Wrap any other return value into a 200 response, equivalent to HttpResults.Ok(...)
                builder.AppendLine($"return {ToResponseCall($"{HttpResultsType}.Ok({(hasFilter ? "ctx.Result" : "__result__")})")};");
            }
        }
    }

    private static string BuildCallArgs(HandlerModel handler, bool hasFilter)
    {
        // バインディング種別とフィルター有無に応じてハンドラー呼び出し用の引数文字列を構築
        // Build the argument string for the handler invocation based on binding kind and filter presence
        var parameters = handler.Parameters;
        var argParts = new List<string>();
        var isEvent = handler.Type == HandlerType.Event;

        for (var i = 0; i < parameters.Count; i++)
        {
            var p = parameters[i];
            switch (p.BindingType)
            {
                case ParameterBindingType.Request:
                    if (isEvent)
                    {
                        argParts.Add(hasFilter ? $"({p.Type.FullName})ctx.Request" : "ev");
                    }
                    else
                    {
                        // フィルター有無に関わらず request 変数は同名でスコープに存在する
                        // (フィルター時は __Inner__ のローカル、非フィルター時はハンドラー引数)
                        // 'request' is in scope either way: a local in __Inner__ (filter) or the handler parameter (no filter)
                        argParts.Add("request");
                    }
                    break;
                case ParameterBindingType.Context:
                    argParts.Add(hasFilter ? "ctx.LambdaContext" : "context");
                    break;
                default:
                    argParts.Add($"p{i}!");
                    break;
            }
        }

        return String.Join(", ", argParts);
    }

    private static string GetEntryRequestType(HandlerModel handler)
    {
        if (handler.Type == HandlerType.Event)
        {
            return handler.GetRequestParam()?.Type.FullName ?? V2RequestType;
        }

        if (handler.Type == HandlerType.HttpApiAuthorizer)
        {
            return handler.GetRequestParam()?.Type.FullName ?? V2AuthorizerRequestType;
        }

        return V2RequestType;
    }

    private static string ToResponseCall(string expression)
    {
        // IHttpResult.ToResponse は明示的実装のため、IHttpResult へキャストして呼び出す
        // IHttpResult.ToResponse is an explicit implementation, so cast to IHttpResult before calling
        return $"(({HttpResultType})({expression})).ToResponse(__lambdaSerializer__)";
    }

    private static string AuthorizerResponseType(HandlerModel handler)
    {
        // EnableSimpleResponses はコンパイル時に確定するため、応答型を静的に選択する
        // EnableSimpleResponses is known at compile time, so the response type is selected statically
        return !handler.EnableSimpleResponses
            ? AuthorizerIamResponseType
            : AuthorizerSimpleResponseType;
    }

    private static string AuthorizerResponseCall(HandlerModel handler, string expression, bool hasFilter)
    {
        // ToSimpleResponse / ToIamResponse は明示的実装のため、IAuthorizerResult へキャストして呼び出す
        // ToSimpleResponse / ToIamResponse are explicit implementations, so cast to IAuthorizerResult before calling
        return !handler.EnableSimpleResponses
            ? $"(({AuthorizerResultType})({expression})).ToIamResponse({GetAuthorizerRouteArnExpression(handler, hasFilter)})"
            : $"(({AuthorizerResultType})({expression})).ToSimpleResponse()";
    }

    private static string GetAuthorizerRouteArnExpression(HandlerModel handler, bool hasFilter)
    {
        return GetEntryRequestType(handler) == V2AuthorizerRequestType
            ? hasFilter ? $"(({V2AuthorizerRequestType})ctx.Request).RouteArn" : "request.RouteArn"
            : "null";
    }
}

internal static class SourceBuilderExtensions
{
    public static void AppendLine(this SourceBuilder builder, string line)
    {
        builder.Indent().Append(line).NewLine();
    }

    public static void BeginBlock(this SourceBuilder builder)
    {
        builder.Indent().Append("{").NewLine();
        builder.IndentLevel++;
    }

    public static void EndBlock(this SourceBuilder builder, bool semicolon = false)
    {
        builder.IndentLevel--;
        builder.Indent();
        if (semicolon)
        {
            builder.Append("};").NewLine();
        }
        else
        {
            builder.Append("}").NewLine();
        }
    }
}
