#pragma warning disable IDE0060, IDE0059, SA1313
namespace AmazonLambdaExtension.Generator;

using AmazonLambdaExtension.Generator.Models;

using SourceGenerateHelper;

internal static class WrapperBuilder
{
    private const string V2RequestType = "global::Amazon.Lambda.APIGatewayEvents.APIGatewayHttpApiV2ProxyRequest";
    private const string V2ResponseType = "global::Amazon.Lambda.APIGatewayEvents.APIGatewayHttpApiV2ProxyResponse";
    private const string LambdaContextType = "global::Amazon.Lambda.Core.ILambdaContext";
    private const string InvocationContextType = "global::AmazonLambdaExtension.Filters.LambdaInvocationContext";
    private const string FilterDelegateType = "global::AmazonLambdaExtension.Filters.LambdaFilterDelegate";
    private const string HttpResultType = "global::AmazonLambdaExtension.APIGateway.IHttpResult";
    private const string HttpResultsType = "global::AmazonLambdaExtension.APIGateway.HttpResults";
    private const string HttpResultOptionsType = "global::AmazonLambdaExtension.APIGateway.HttpResultSerializationOptions";
    private const string AuthorizerResultType = "global::AmazonLambdaExtension.APIGateway.IAuthorizerResult";
    private const string AuthorizerResultsType = "global::AmazonLambdaExtension.APIGateway.AuthorizerResults";
    private const string AuthorizerResultOptionsType = "global::AmazonLambdaExtension.APIGateway.AuthorizerResultSerializationOptions";
    private const string AuthorizerFormatType = "global::AmazonLambdaExtension.APIGateway.AuthorizerResultSerializationOptions.AuthorizerFormat";
    private const string StringConverterType = "global::AmazonLambdaExtension.Binders.StringConverter";
    private const string ValidationHelperType = "global::AmazonLambdaExtension.Helpers.ValidationHelper";
    private const string ApiExceptionType = "global::AmazonLambdaExtension.ApiException";
    private const string StreamType = "global::System.IO.Stream";
    private const string GetRequiredService = "global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService";
    private const string BuildServiceProvider = "global::Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider";

    public static void BuildShared(SourceBuilder builder, LambdaModel model)
    {
        builder.AutoGenerated();
        builder.EnableNullable();
        builder.NewLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            builder.Namespace(model.Namespace);
            builder.NewLine();
        }

        var classKeyword = model.IsValueType ? "struct" : "class";
        builder.AppendLine($"partial {classKeyword} {model.ClassName}");
        builder.BeginBlock();

        BuildStaticFields(builder, model);

        builder.EndBlock();
    }

    public static void Build(SourceBuilder builder, LambdaModel model, HandlerModel handler)
    {
        builder.AutoGenerated();
        builder.EnableNullable();
        builder.NewLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            builder.Namespace(model.Namespace);
            builder.NewLine();
        }

        var classKeyword = model.IsValueType ? "struct" : "class";
        builder.AppendLine($"partial {classKeyword} {model.ClassName}");
        builder.BeginBlock();

        if (model.Filters.AsArray().Length > 0)
        {
            BuildInnerMethod(builder, model, handler);
            builder.NewLine();
            BuildPipeline(builder, model, handler);
            builder.NewLine();
        }

        BuildHandlerMethod(builder, model, handler);

        builder.EndBlock();
    }

    private static void BuildStaticFields(SourceBuilder builder, LambdaModel model)
    {
        var handlers = model.Handlers.AsArray();
        var hasHttpHandler = handlers.Any(static h =>
            h.Kind == HandlerKind.HttpApi ||
            h.Kind == HandlerKind.FunctionUrl ||
            h.Kind == HandlerKind.HttpApiAuthorizer);
        var hasBodyParam = handlers.Any(static h =>
            h.Parameters.AsArray().Any(static p => p.BindingKind == ParameterBindingKind.FromBody));

        if (model.ServiceResolver != null)
        {
            builder.AppendLine($"private static readonly global::System.IServiceProvider __provider__ =");
            builder.AppendLine($"    {BuildServiceProvider}({model.ServiceResolver.Type.FullName}.ConfigureServices());");
            builder.NewLine();

            // target
            var ctorArgs = string.Join(", ", model.ConstructorParameters.AsArray().Select(static (p, _) => $"{GetRequiredService}<{p.FullName}>(__provider__)"));
            builder.AppendLine($"private static readonly {model.FunctionType.FullName} __target__ = new {model.FunctionType.FullName}({ctorArgs});");
        }
        else
        {
            builder.AppendLine($"private static readonly {model.FunctionType.FullName} __target__ = new {model.FunctionType.FullName}();");
        }

        if (hasHttpHandler)
        {
            builder.NewLine();
            if (model.ServiceResolver != null)
            {
                builder.AppendLine($"private static readonly global::Amazon.Lambda.Core.ILambdaSerializer __lambdaSerializer__ =");
                builder.AppendLine($"    {GetRequiredService}<global::Amazon.Lambda.Core.ILambdaSerializer>(__provider__);");
            }
            else
            {
                builder.AppendLine($"private static readonly global::Amazon.Lambda.Core.ILambdaSerializer __lambdaSerializer__ =");
                builder.AppendLine($"    new global::Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer();");
            }
        }

        if (hasBodyParam && model.ServiceResolver != null)
        {
            builder.NewLine();
            builder.AppendLine($"private static readonly global::AmazonLambdaExtension.Serialization.IBodySerializer __bodySerializer__ =");
            builder.AppendLine($"    {GetRequiredService}<global::AmazonLambdaExtension.Serialization.IBodySerializer>(__provider__);");
        }

        foreach (var filter in model.Filters.AsArray())
        {
            builder.NewLine();
            if (model.ServiceResolver != null)
            {
                builder.AppendLine($"private static readonly {filter.FilterType.FullName} __filter{filter.Index}__ =");
                builder.AppendLine($"    {GetRequiredService}<{filter.FilterType.FullName}>(__provider__);");
            }
            else
            {
                builder.AppendLine($"private static readonly {filter.FilterType.FullName} __filter{filter.Index}__ = new {filter.FilterType.FullName}();");
            }
        }
    }

    private static void BuildInnerMethod(SourceBuilder builder, LambdaModel model, HandlerModel handler)
    {
        var methodName = handler.MethodName;
        builder.AppendLine($"private static async global::System.Threading.Tasks.ValueTask __{methodName}_Inner__(");
        builder.AppendLine($"    {InvocationContextType} ctx)");
        builder.BeginBlock();

        if (handler.Kind != HandlerKind.Event)
        {
            builder.AppendLine($"var request = ({V2RequestType})ctx.Request;");
            builder.NewLine();
        }
        else
        {
            // Get event type
            var eventParam = GetRequestParam(handler);
            if (eventParam != null)
            {
                builder.AppendLine($"var ev = ({eventParam.Type.FullName})ctx.Request;");
                builder.NewLine();
            }
        }

        BuildParameterBindings(builder, handler, hasFilter: true);

        BuildHandlerInvocation(builder, model, handler, hasFilter: true);

        builder.EndBlock();
    }

    private static void BuildPipeline(SourceBuilder builder, LambdaModel model, HandlerModel handler)
    {
        var methodName = handler.MethodName;
        var pascal = ToPascalCase(methodName);
        builder.AppendLine($"private static readonly {FilterDelegateType} __{methodName}_Pipeline__ = Build{pascal}Pipeline();");
        builder.NewLine();
        builder.AppendLine($"private static {FilterDelegateType} Build{pascal}Pipeline()");
        builder.BeginBlock();

        var filters = model.Filters.AsArray();
        builder.AppendLine($"{FilterDelegateType} p = __{methodName}_Inner__;");
        builder.NewLine();

        for (var i = filters.Length - 1; i >= 0; i--)
        {
            var idx = filters[i].Index;
            builder.AppendLine($"var inner{i} = p;");
            builder.AppendLine($"p = ctx => __filter{idx}__.InvokeAsync(ctx, inner{i});");
            if (i > 0) builder.NewLine();
        }

        builder.NewLine();
        builder.AppendLine("return p;");
        builder.EndBlock();
    }

    private static void BuildHandlerMethod(SourceBuilder builder, LambdaModel model, HandlerModel handler)
    {
        var methodName = handler.MethodName;
        var filters = model.Filters.AsArray();
        var hasFilters = filters.Length > 0;

        string returnType;
        if (handler.Kind == HandlerKind.HttpApi || handler.Kind == HandlerKind.FunctionUrl ||
            handler.Kind == HandlerKind.HttpApiAuthorizer)
        {
            if (handler.ReturnsHttpResult || handler.Kind == HandlerKind.HttpApiAuthorizer)
            {
                returnType = $"global::System.Threading.Tasks.Task<{StreamType}>";
            }
            else
            {
                returnType = $"global::System.Threading.Tasks.Task<{V2ResponseType}>";
            }
        }
        else
        {
            if (handler.ResultType != null)
            {
                returnType = $"global::System.Threading.Tasks.Task<{handler.ResultType.FullName}>";
            }
            else
            {
                returnType = "global::System.Threading.Tasks.Task";
            }
        }

        builder.AppendLine($"public static async {returnType} {methodName}_Handler(");

        if (handler.Kind == HandlerKind.Event)
        {
            // Determine request param type
            var requestParam = GetRequestParam(handler);
            var reqTypeName = requestParam?.Type.FullName ?? V2RequestType;
            builder.AppendLine($"    {reqTypeName} ev,");
            builder.AppendLine($"    {LambdaContextType} context)");
        }
        else
        {
            builder.AppendLine($"    {V2RequestType} request,");
            builder.AppendLine($"    {LambdaContextType} context)");
        }

        builder.BeginBlock();

        if (hasFilters)
        {
            builder.AppendLine($"var ctx = new {InvocationContextType}");
            builder.BeginBlock();

            if (handler.Kind == HandlerKind.Event)
                builder.AppendLine("Request = ev,");
            else
                builder.AppendLine("Request = request,");

            builder.AppendLine("LambdaContext = context,");
            builder.AppendLine("CancellationToken = default,");
            builder.EndBlock(semicolon: true);
            builder.NewLine();

            BuildTryCatchWithFilter(builder, handler);
        }
        else
        {
            if (handler.Kind == HandlerKind.Event)
            {
                BuildEventTryCatch(builder, model, handler, false);
            }
            else
            {
                BuildHttpTryCatch(builder, model, handler, false);
            }
        }

        builder.EndBlock();
    }

    private static void BuildTryCatchWithFilter(SourceBuilder builder, HandlerModel handler)
    {
        builder.AppendLine("try");
        builder.BeginBlock();
        builder.AppendLine($"await __{handler.MethodName}_Pipeline__(ctx);");
        builder.EndBlock();

        if (handler.Kind == HandlerKind.HttpApiAuthorizer)
        {
            builder.AppendLine("catch (global::System.Exception ex)");
            builder.BeginBlock();
            builder.AppendLine("context.Logger.LogLine(ex.ToString());");
            var format = handler.Authorizer?.EnableSimpleResponses == false
                ? $"{AuthorizerFormatType}.HttpApiIamPolicy"
                : $"{AuthorizerFormatType}.HttpApiSimple";
            builder.AppendLine($"return {AuthorizerResultsType}.Deny()");
            builder.AppendLine($"    .Serialize(new {AuthorizerResultOptionsType}");
            builder.BeginBlock();
            builder.AppendLine($"Format = {format},");
            builder.AppendLine("RouteArn = null");
            builder.EndBlock(semicolon: false);
            builder.AppendLine(");");
            builder.EndBlock();
        }
        else if (handler.Kind == HandlerKind.HttpApi || handler.Kind == HandlerKind.FunctionUrl)
        {
            builder.AppendLine($"catch ({ApiExceptionType} ex)");
            builder.BeginBlock();
            if (handler.ReturnsHttpResult)
            {
                builder.AppendLine($"return {HttpResultsType}.NewResult((global::System.Net.HttpStatusCode)ex.StatusCode, ex.Message)");
                builder.AppendLine($"    .Serialize(new {HttpResultOptionsType} {{ Serializer = __lambdaSerializer__ }});");
            }
            else
            {
                builder.AppendLine($"return new {V2ResponseType} {{ StatusCode = (int)ex.StatusCode, Body = ex.Message }};");
            }
            builder.EndBlock();

            builder.AppendLine("catch (global::System.Exception ex)");
            builder.BeginBlock();
            builder.AppendLine("context.Logger.LogLine(ex.ToString());");
            if (handler.ReturnsHttpResult)
            {
                builder.AppendLine($"return {HttpResultsType}.InternalServerError()");
                builder.AppendLine($"    .Serialize(new {HttpResultOptionsType} {{ Serializer = __lambdaSerializer__ }});");
            }
            else
            {
                builder.AppendLine($"return new {V2ResponseType} {{ StatusCode = 500 }};");
            }
            builder.EndBlock();
        }
        else
        {
            builder.AppendLine("catch (global::System.Exception ex)");
            builder.BeginBlock();
            builder.AppendLine("context.Logger.LogLine(ex.ToString());");
            builder.AppendLine("throw;");
            builder.EndBlock();
        }

        builder.NewLine();
        BuildResultExtraction(builder, handler, hasFilter: true);
    }

    private static void BuildHttpTryCatch(SourceBuilder builder, LambdaModel model, HandlerModel handler, bool _hasFilter)
    {
        builder.AppendLine("try");
        builder.BeginBlock();

        BuildParameterBindings(builder, handler, hasFilter: false);
        BuildHandlerInvocation(builder, model, handler, hasFilter: false);

        builder.EndBlock();

        if (handler.Kind == HandlerKind.HttpApiAuthorizer)
        {
            builder.AppendLine("catch (global::System.Exception ex)");
            builder.BeginBlock();
            builder.AppendLine("context.Logger.LogLine(ex.ToString());");
            var format = handler.Authorizer?.EnableSimpleResponses == false
                ? $"{AuthorizerFormatType}.HttpApiIamPolicy"
                : $"{AuthorizerFormatType}.HttpApiSimple";
            builder.AppendLine($"return {AuthorizerResultsType}.Deny()");
            builder.AppendLine($"    .Serialize(new {AuthorizerResultOptionsType}");
            builder.BeginBlock();
            builder.AppendLine($"Format = {format},");
            builder.AppendLine("RouteArn = null");
            builder.EndBlock(semicolon: false);
            builder.AppendLine(");");
            builder.EndBlock();
        }
        else
        {
            builder.AppendLine($"catch ({ApiExceptionType} ex)");
            builder.BeginBlock();
            if (handler.ReturnsHttpResult)
            {
                builder.AppendLine($"return {HttpResultsType}.NewResult((global::System.Net.HttpStatusCode)ex.StatusCode, ex.Message)");
                builder.AppendLine($"    .Serialize(new {HttpResultOptionsType} {{ Serializer = __lambdaSerializer__ }});");
            }
            else
            {
                builder.AppendLine($"return new {V2ResponseType} {{ StatusCode = (int)ex.StatusCode, Body = ex.Message }};");
            }
            builder.EndBlock();

            builder.AppendLine("catch (global::System.Exception ex)");
            builder.BeginBlock();
            builder.AppendLine("context.Logger.LogLine(ex.ToString());");
            if (handler.ReturnsHttpResult)
            {
                builder.AppendLine($"return {HttpResultsType}.InternalServerError()");
                builder.AppendLine($"    .Serialize(new {HttpResultOptionsType} {{ Serializer = __lambdaSerializer__ }});");
            }
            else
            {
                builder.AppendLine($"return new {V2ResponseType} {{ StatusCode = 500 }};");
            }
            builder.EndBlock();
        }
    }

    private static void BuildEventTryCatch(SourceBuilder builder, LambdaModel model, HandlerModel handler, bool _hasFilter)
    {
        builder.AppendLine("try");
        builder.BeginBlock();

        BuildHandlerInvocationDirect(builder, model, handler);

        builder.EndBlock();
        builder.AppendLine("catch (global::System.Exception ex)");
        builder.BeginBlock();
        builder.AppendLine("context.Logger.LogLine(ex.ToString());");
        builder.AppendLine("throw;");
        builder.EndBlock();
    }

    private static void BuildParameterBindings(SourceBuilder builder, HandlerModel handler, bool hasFilter)
    {
        var parameters = handler.Parameters.AsArray();
        for (var i = 0; i < parameters.Length; i++)
        {
            var p = parameters[i];
            BuildParameterBinding(builder, handler, p, i, hasFilter);
        }
    }

    private static void BuildParameterBinding(SourceBuilder builder, HandlerModel handler, ParameterModel param, int index, bool hasFilter)
    {
        var pVar = $"p{index}";
        var pRaw = $"p{index}raw";
        var requestVar = hasFilter ? "request" : "request";
        var typeName = param.Type.FullName;
        var key = param.Key;

        string BadRequest400(string paramName)
        {
            if (handler.ReturnsHttpResult)
            {
                return $"return {HttpResultsType}.BadRequest($\"Invalid parameter: {paramName}\")" +
                       $".Serialize(new {HttpResultOptionsType} {{ Serializer = __lambdaSerializer__ }});";
            }
            else
            {
                return $"return new {V2ResponseType} {{ StatusCode = 400, " +
                       $"Body = $\"Invalid parameter: {paramName}\" }};";
            }
        }

        switch (param.BindingKind)
        {
            case ParameterBindingKind.Request:
                // already in scope as 'request'
                return;

            case ParameterBindingKind.Context:
                // already in scope as 'context'
                return;

            case ParameterBindingKind.FromServices:
                builder.AppendLine($"var {pVar} = {GetRequiredService}<{typeName}>(__provider__);");
                builder.NewLine();
                return;

            case ParameterBindingKind.FromBody:
                builder.AppendLine($"var {pVar} = __bodySerializer__.Deserialize<{typeName}>({requestVar}.Body ?? string.Empty);");
                if (!param.SkipValidation)
                {
                    builder.AppendLine($"if ({pVar} is not null && !{ValidationHelperType}.Validate({pVar}))");
                    builder.BeginBlock();
                    if (hasFilter)
                    {
                        builder.AppendLine($"ctx.Result = {HttpResultsType}.BadRequest(\"Validation failed: {param.Name}\");");
                        builder.AppendLine("return;");
                    }
                    else
                    {
                        builder.AppendLine($"{BadRequest400(param.Name)}");
                    }
                    builder.EndBlock();
                }
                builder.NewLine();
                return;

            case ParameterBindingKind.FromCustomAuthorizer:
                builder.AppendLine($"var {pVar} = default({typeName});");
                builder.AppendLine($"if ({requestVar}.RequestContext?.Authorizer?.Lambda is not null &&");
                builder.AppendLine($"    {requestVar}.RequestContext.Authorizer.Lambda.TryGetValue(\"{key}\", out var {pRaw}ca) &&");
                builder.AppendLine($"    {pRaw}ca is not null)");
                builder.BeginBlock();
                if (string.IsNullOrEmpty(param.ConverterMethod))
                {
                    builder.AppendLine($"{pVar} = {pRaw}ca as {typeName};");
                }
                else
                {
                    var isEnum = param.ConverterMethod == "TryToEnum";
                    var converterCall = isEnum
                        ? $"{StringConverterType}.TryToEnum<{GetBaseTypeName(param.Type)}>(({pRaw}ca as string ?? string.Empty).AsSpan(), out var {pVar}tmp)"
                        : $"{StringConverterType}.{param.ConverterMethod}(({pRaw}ca as string ?? string.Empty).AsSpan(), out var {pVar}tmp)";
                    builder.AppendLine($"if (!{converterCall})");
                    builder.BeginBlock();
                    if (hasFilter)
                    {
                        builder.AppendLine($"ctx.Result = {HttpResultsType}.BadRequest($\"Invalid parameter: {key}\");");
                        builder.AppendLine("return;");
                    }
                    else
                    {
                        builder.AppendLine(BadRequest400(key));
                    }
                    builder.EndBlock();
                    builder.AppendLine($"{pVar} = {pVar}tmp;");
                }
                builder.EndBlock();
                builder.NewLine();
                return;

            case ParameterBindingKind.FromRoute:
                BuildScalarOrArrayBinding(
                    builder,
                    handler,
                    param,
                    index,
                    hasFilter,
                    $"{requestVar}.PathParameters",
                    "PathParameters");
                return;

            case ParameterBindingKind.FromQuery:
                BuildScalarOrArrayBinding(
                    builder,
                    handler,
                    param,
                    index,
                    hasFilter,
                    $"{requestVar}.QueryStringParameters",
                    "QueryStringParameters");
                return;

            case ParameterBindingKind.FromHeader:
                BuildScalarOrArrayBinding(
                    builder,
                    handler,
                    param,
                    index,
                    hasFilter,
                    $"{requestVar}.Headers",
                    "Headers");
                return;
        }
    }

    private static void BuildScalarOrArrayBinding(SourceBuilder builder, HandlerModel handler, ParameterModel param, int index, bool hasFilter, string dictExpr, string _dictName)
    {
        var pVar = $"p{index}";
        var pRaw = $"p{index}raw";
        var typeName = param.Type.FullName;
        var key = param.Key;

        string Bad400()
        {
            if (handler.ReturnsHttpResult)
            {
                return $"return {HttpResultsType}.BadRequest($\"Invalid parameter: {key}\")" +
                       $".Serialize(new {HttpResultOptionsType} {{ Serializer = __lambdaSerializer__ }});";
            }
            else
            {
                return $"return new {V2ResponseType} {{ StatusCode = 400, Body = $\"Invalid parameter: {key}\" }};";
            }
        }

        if (param.Type.IsArray && param.Type.ElementType != null)
        {
            var elemType = param.Type.ElementType.FullName;
            var converterMethod = param.ConverterMethod;
            builder.AppendLine($"var {pVar} = global::System.Array.Empty<{elemType}>();");
            builder.AppendLine($"if ({dictExpr} is not null &&");
            builder.AppendLine($"    {dictExpr}.TryGetValue(\"{key}\", out var {pRaw}) &&");
            builder.AppendLine($"    {pRaw} is not null)");
            builder.BeginBlock();
            builder.AppendLine($"var {pVar}parts = {pRaw}.Split(',');");
            builder.AppendLine($"{pVar} = new {elemType}[{pVar}parts.Length];");
            builder.AppendLine($"for (var i = 0; i < {pVar}parts.Length; i++)");
            builder.BeginBlock();
            if (string.IsNullOrEmpty(converterMethod))
            {
                builder.AppendLine($"{pVar}[i] = {pVar}parts[i];");
            }
            else
            {
                var isEnum = converterMethod == "TryToEnum";
                var converterCall = isEnum
                    ? $"!{StringConverterType}.TryToEnum<{elemType}>({pVar}parts[i].AsSpan(), out {pVar}[i])"
                    : $"!{StringConverterType}.{converterMethod}({pVar}parts[i].AsSpan(), out {pVar}[i])";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = {HttpResultsType}.BadRequest($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine(Bad400());
                }
                builder.EndBlock();
            }
            builder.EndBlock();
            builder.EndBlock();
            builder.NewLine();
        }
        else if (param.Type.IsNullable && param.Type.UnderlyingType != null)
        {
            // Nullable<T>
            var baseType = param.Type.UnderlyingType.FullName;
            var converterMethod = param.ConverterMethod;
            builder.AppendLine($"var {pVar} = ({typeName})null;");
            builder.AppendLine($"if ({dictExpr} is not null &&");
            builder.AppendLine($"    {dictExpr}.TryGetValue(\"{key}\", out var {pRaw}) &&");
            builder.AppendLine($"    {pRaw} is not null)");
            builder.BeginBlock();
            if (string.IsNullOrEmpty(converterMethod))
            {
                builder.AppendLine($"{pVar} = {pRaw};");
            }
            else
            {
                var isEnum = converterMethod == "TryToEnum";
                var converterCall = isEnum
                    ? $"!{StringConverterType}.TryToEnum<{baseType}>({pRaw}.AsSpan(), out var {pVar}tmp)"
                    : $"!{StringConverterType}.{converterMethod}({pRaw}.AsSpan(), out var {pVar}tmp)";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = {HttpResultsType}.BadRequest($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine(Bad400());
                }
                builder.EndBlock();
                builder.AppendLine($"{pVar} = {pVar}tmp;");
            }
            builder.EndBlock();
            builder.NewLine();
        }
        else
        {
            // Scalar
            var converterMethod = param.ConverterMethod;
            if (string.IsNullOrEmpty(converterMethod))
            {
                // string
                builder.AppendLine($"var {pVar} = default({typeName})!;");
                builder.AppendLine($"if ({dictExpr} is not null &&");
                builder.AppendLine($"    {dictExpr}.TryGetValue(\"{key}\", out var {pRaw}))");
                builder.BeginBlock();
                builder.AppendLine($"{pVar} = {pRaw};");
                builder.EndBlock();
                builder.NewLine();
            }
            else
            {
                builder.AppendLine($"var {pVar} = default({typeName});");
                builder.AppendLine($"if ({dictExpr} is not null &&");
                builder.AppendLine($"    {dictExpr}.TryGetValue(\"{key}\", out var {pRaw}) &&");
                builder.AppendLine($"    {pRaw} is not null)");
                builder.BeginBlock();
                var isEnum = converterMethod == "TryToEnum";
                var converterCall = isEnum
                    ? $"!{StringConverterType}.TryToEnum<{typeName}>({pRaw}.AsSpan(), out {pVar})"
                    : $"!{StringConverterType}.{converterMethod}({pRaw}.AsSpan(), out {pVar})";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = {HttpResultsType}.BadRequest($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine(Bad400());
                }
                builder.EndBlock();
                builder.EndBlock();
                builder.NewLine();
            }
        }
    }

    private static void BuildHandlerInvocation(SourceBuilder builder, LambdaModel _model, HandlerModel handler, bool hasFilter)
    {
        var args = BuildCallArgs(handler, hasFilter);
        var awaitPrefix = handler.IsAsync ? "await " : string.Empty;

        if (handler.Kind == HandlerKind.Event)
        {
            if (handler.ResultType != null)
            {
                builder.AppendLine($"var __result__ = {awaitPrefix}__target__.{handler.MethodName}({args});");
                if (hasFilter)
                {
                    builder.AppendLine("ctx.Result = __result__;");
                }
                else
                {
                    builder.AppendLine("return __result__;");
                }
            }
            else
            {
                builder.AppendLine($"{awaitPrefix}__target__.{handler.MethodName}({args});");
            }

            return;
        }

        builder.AppendLine($"var __result__ = {awaitPrefix}__target__.{handler.MethodName}({args});");

        if (hasFilter)
        {
            builder.AppendLine("ctx.Result = __result__;");
        }
        else
        {
            BuildResultExtraction(builder, handler, hasFilter: false);
        }
    }

    private static void BuildHandlerInvocationDirect(SourceBuilder builder, LambdaModel _model, HandlerModel handler)
    {
        // For Event handler without filter
        var awaitPrefix = handler.IsAsync ? "await " : string.Empty;
        var parameters = handler.Parameters.AsArray();
        var argParts = new System.Collections.Generic.List<string>();

        for (var i = 0; i < parameters.Length; i++)
        {
            var p = parameters[i];
            switch (p.BindingKind)
            {
                case ParameterBindingKind.Request:
                    argParts.Add("ev");
                    break;
                case ParameterBindingKind.Context:
                    argParts.Add("context");
                    break;
                case ParameterBindingKind.FromServices:
                    argParts.Add($"p{i}");
                    break;
                default:
                    argParts.Add($"p{i}");
                    break;
            }
        }

        if (handler.ResultType != null)
        {
            builder.AppendLine($"var __result__ = {awaitPrefix}__target__.{handler.MethodName}({string.Join(", ", argParts)});");
        }
        else
        {
            builder.AppendLine($"{awaitPrefix}__target__.{handler.MethodName}({string.Join(", ", argParts)});");
        }
    }

    private static void BuildResultExtraction(SourceBuilder builder, HandlerModel handler, bool hasFilter)
    {
        if (handler.Kind == HandlerKind.HttpApiAuthorizer)
        {
            var format = handler.Authorizer?.EnableSimpleResponses == false
                ? $"{AuthorizerFormatType}.HttpApiIamPolicy"
                : $"{AuthorizerFormatType}.HttpApiSimple";

            if (hasFilter)
            {
                builder.AppendLine($"var result = ({AuthorizerResultType})ctx.Result!;");
                builder.AppendLine($"return result.Serialize(new {AuthorizerResultOptionsType}");
                builder.BeginBlock();
                builder.AppendLine($"Format = {format},");
                builder.AppendLine("RouteArn = null");
                builder.EndBlock(semicolon: false);
                builder.AppendLine(");");
            }
            else
            {
                builder.AppendLine($"return __result__.Serialize(new {AuthorizerResultOptionsType}");
                builder.BeginBlock();
                builder.AppendLine($"Format = {format},");
                builder.AppendLine("RouteArn = null");
                builder.EndBlock(semicolon: false);
                builder.AppendLine(");");
            }
        }
        else if (handler.Kind == HandlerKind.HttpApi || handler.Kind == HandlerKind.FunctionUrl)
        {
            if (handler.ReturnsHttpResult)
            {
                if (hasFilter)
                {
                    builder.AppendLine($"if (ctx.Result is {HttpResultType} httpResult)");
                    builder.BeginBlock();
                    builder.AppendLine($"return httpResult.Serialize(new {HttpResultOptionsType} {{ Serializer = __lambdaSerializer__ }});");
                    builder.EndBlock();
                    builder.NewLine();
                    builder.AppendLine($"return {HttpResultsType}.InternalServerError()");
                    builder.AppendLine($"    .Serialize(new {HttpResultOptionsType} {{ Serializer = __lambdaSerializer__ }});");
                }
                else
                {
                    builder.AppendLine($"return __result__.Serialize(new {HttpResultOptionsType} {{ Serializer = __lambdaSerializer__ }});");
                }
            }
            else
            {
                if (hasFilter)
                {
                    builder.AppendLine($"return ({V2ResponseType})ctx.Result!;");
                }
                else
                {
                    builder.AppendLine("return __result__;");
                }
            }
        }
    }

    private static string BuildCallArgs(HandlerModel handler, bool hasFilter)
    {
        var parameters = handler.Parameters.AsArray();
        var argParts = new System.Collections.Generic.List<string>();
        var isEvent = handler.Kind == HandlerKind.Event;

        for (var i = 0; i < parameters.Length; i++)
        {
            var p = parameters[i];
            switch (p.BindingKind)
            {
                case ParameterBindingKind.Request:
                    if (isEvent)
                        argParts.Add(hasFilter ? $"({p.Type.FullName})ctx.Request" : "ev");
                    else
                        argParts.Add(hasFilter ? "request" : "request");
                    break;
                case ParameterBindingKind.Context:
                    argParts.Add(hasFilter ? "ctx.LambdaContext" : "context");
                    break;
                default:
                    argParts.Add($"p{i}!");
                    break;
            }
        }

        return string.Join(", ", argParts);
    }

    private static ParameterModel? GetRequestParam(HandlerModel handler)
    {
        foreach (var p in handler.Parameters.AsArray())
        {
            if (p.BindingKind == ParameterBindingKind.Request)
            {
                return p;
            }
        }
        return null;
    }

    private static string GetBaseTypeName(TypeRefModel type)
    {
        if (type.IsNullable && type.UnderlyingType != null)
        {
            return type.UnderlyingType.FullName;
        }

        if (type.IsArray && type.ElementType != null)
        {
            return type.ElementType.FullName;
        }

        return type.FullName;
    }

    private static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }

        return char.ToUpperInvariant(name[0]) + name.Substring(1);
    }
}

internal static class SourceBuilderExtensions
{
    public static void AppendLine(this SourceBuilder builder, string line)
    {
        builder.Append(line).NewLine();
    }

    public static void BeginBlock(this SourceBuilder builder)
    {
        builder.Indent().Append("{").NewLine();
        builder.IndentLevel++;
    }

    public static void EndBlock(this SourceBuilder builder, bool semicolon = false)
    {
        builder.IndentLevel--;
        builder.Indent();
        if (semicolon)
            builder.Append("};").NewLine();
        else
            builder.Append("}").NewLine();
    }
}
