#pragma warning disable IDE0060, IDE0059, SA1313
namespace AmazonLambdaExtension.Generator;

using AmazonLambdaExtension.Generator.Models;

using SourceGenerateHelper;

internal static class WrapperBuilder
{
    private const string V2RequestType = "global::Amazon.Lambda.APIGatewayEvents.APIGatewayHttpApiV2ProxyRequest";
    private const string V2ResponseType = "global::Amazon.Lambda.APIGatewayEvents.APIGatewayHttpApiV2ProxyResponse";
    private const string LambdaContextType = "global::Amazon.Lambda.Core.ILambdaContext";
    private const string InvocationContextType = "global::AmazonLambdaExtension.Filters.LambdaInvocationContext";
    private const string FilterDelegateType = "global::AmazonLambdaExtension.Filters.LambdaFilterDelegate";
    private const string HttpResultType = "global::AmazonLambdaExtension.APIGateway.IHttpResult";
    private const string HttpResultsType = "global::AmazonLambdaExtension.APIGateway.HttpResults";
    private const string HttpResultOptionsType = "global::AmazonLambdaExtension.APIGateway.HttpResultSerializationOptions";
    private const string AuthorizerResultType = "global::AmazonLambdaExtension.APIGateway.IAuthorizerResult";
    private const string AuthorizerResultsType = "global::AmazonLambdaExtension.APIGateway.AuthorizerResults";
    private const string AuthorizerResultOptionsType = "global::AmazonLambdaExtension.APIGateway.AuthorizerResultSerializationOptions";
    private const string AuthorizerFormatType = "global::AmazonLambdaExtension.APIGateway.AuthorizerResultSerializationOptions.AuthorizerFormat";
    private const string StringConverterType = "global::AmazonLambdaExtension.Binders.StringConverter";
    private const string RequestValidatorType = "global::AmazonLambdaExtension.Validation.IRequestValidator";
    private const string ApiExceptionType = "global::AmazonLambdaExtension.ApiException";
    private const string StreamType = "global::System.IO.Stream";
    private const string GetRequiredService = "global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService";
    private const string BuildServiceProvider = "global::Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider";

    public static void BuildShared(SourceBuilder builder, LambdaModel model)
    {
        // 全ハンドラー共通の静的フィールド(ターゲット・シリアライザー等)を含む partial クラスを生成
        // Generate the partial class containing static fields shared across all handlers
        builder.AutoGenerated();
        builder.EnableNullable();
        builder.NewLine();

        if (!String.IsNullOrEmpty(model.Namespace))
        {
            builder.Namespace(model.Namespace);
            builder.NewLine();
        }

        var classKeyword = model.IsValueType ? "struct" : "class";
        builder.AppendLine($"partial {classKeyword} {model.ClassName}");
        builder.BeginBlock();

        BuildStaticFields(builder, model);

        builder.EndBlock();
    }

    public static void Build(SourceBuilder builder, LambdaModel model, HandlerModel handler)
    {
        // 指定ハンドラー向けのラッパーメソッドを含む partial クラスを生成
        // Generate the partial class with the wrapper method for the specified handler
        builder.AutoGenerated();
        builder.EnableNullable();
        builder.NewLine();

        if (!String.IsNullOrEmpty(model.Namespace))
        {
            builder.Namespace(model.Namespace);
            builder.NewLine();
        }

        var classKeyword = model.IsValueType ? "struct" : "class";
        builder.AppendLine($"partial {classKeyword} {model.ClassName}");
        builder.BeginBlock();

        if (model.Filters.Count > 0)
        {
            BuildInnerMethod(builder, handler);
            builder.NewLine();
            BuildPipeline(builder, model, handler);
            builder.NewLine();
        }

        BuildHandlerMethod(builder, model, handler);

        builder.EndBlock();
    }

    private static void BuildStaticFields(SourceBuilder builder, LambdaModel model)
    {
        // ハンドラーの使用状況を事前チェックして必要なフィールドの要否を判定
        // Pre-check handler usage to determine which static fields are required
        var handlers = model.Handlers;
        var hasHttpHandler = handlers.Any(static h =>
            (h.Kind == HandlerKind.HttpApi) ||
            (h.Kind == HandlerKind.FunctionUrl) ||
            (h.Kind == HandlerKind.HttpApiAuthorizer));
        var hasBodyParam = handlers.Any(static h =>
            h.Parameters.Any(static p => p.BindingKind == ParameterBindingKind.FromBody));
        var hasValidation = handlers.Any(static h =>
            h.Parameters.Any(static p => (p.BindingKind == ParameterBindingKind.FromBody) && !p.SkipValidation));

        if (model.ServiceResolver != null)
        {
            // DIコンテナを構築し、コンストラクタ DI でターゲットインスタンスを生成
            // Build DI container and create target instance via constructor injection
            builder.AppendLine($"private static readonly global::System.IServiceProvider __provider__ =");
            builder.AppendLine($"    {BuildServiceProvider}({model.ServiceResolver.Type.FullName}.ConfigureServices());");
            builder.NewLine();

            // target
            var ctorArgs = String.Join(", ", model.ConstructorParameters.Select(static (p, _) => $"{GetRequiredService}<{p.FullName}>(__provider__)"));
            builder.AppendLine($"private static readonly {model.FunctionType.FullName} __target__ = new {model.FunctionType.FullName}({ctorArgs});");
        }
        else
        {
            // DIなしでデフォルトコンストラクタでターゲットインスタンスを生成
            // Create target instance with default constructor (no DI)
            builder.AppendLine($"private static readonly {model.FunctionType.FullName} __target__ = new {model.FunctionType.FullName}();");
        }

        if (hasHttpHandler)
        {
            builder.NewLine();
            if (model.ServiceResolver != null)
            {
                // DIから ILambdaSerializer を解決
                // Resolve ILambdaSerializer from DI container
                builder.AppendLine($"private static readonly global::Amazon.Lambda.Core.ILambdaSerializer __lambdaSerializer__ =");
                builder.AppendLine($"    {GetRequiredService}<global::Amazon.Lambda.Core.ILambdaSerializer>(__provider__);");
            }
            else
            {
                // DIなしの場合はデフォルトの JSON シリアライザーを使用
                // Use default JSON serializer when no DI is configured
                builder.AppendLine($"private static readonly global::Amazon.Lambda.Core.ILambdaSerializer __lambdaSerializer__ =");
                builder.AppendLine($"    new global::Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer();");
            }
        }

        if (hasBodyParam && model.ServiceResolver != null)
        {
            // DIから IBodySerializer を解決
            // Resolve IBodySerializer from DI container
            builder.NewLine();
            builder.AppendLine($"private static readonly global::AmazonLambdaExtension.Serialization.IBodySerializer __bodySerializer__ =");
            builder.AppendLine($"    {GetRequiredService}<global::AmazonLambdaExtension.Serialization.IBodySerializer>(__provider__);");
        }

        if (hasValidation && model.ServiceResolver != null)
        {
            // DIからリクエストバリデーターを解決
            // Resolve IRequestValidator from DI container
            builder.NewLine();
            builder.AppendLine($"private static readonly {RequestValidatorType} __requestValidator__ =");
            builder.AppendLine($"    {GetRequiredService}<{RequestValidatorType}>(__provider__);");
        }

        foreach (var filter in model.Filters)
        {
            builder.NewLine();
            if (model.ServiceResolver != null)
            {
                // DIからフィルターインスタンスを解決
                // Resolve filter instance from DI container
                builder.AppendLine($"private static readonly {filter.FilterType.FullName} __filter{filter.Index}__ =");
                builder.AppendLine($"    {GetRequiredService}<{filter.FilterType.FullName}>(__provider__);");
            }
            else
            {
                // DIなしの場合はデフォルトコンストラクタでフィルターインスタンスを生成
                // Instantiate filter with default constructor (no DI)
                builder.AppendLine($"private static readonly {filter.FilterType.FullName} __filter{filter.Index}__ = new {filter.FilterType.FullName}();");
            }
        }
    }

    private static void BuildInnerMethod(SourceBuilder builder, HandlerModel handler)
    {
        // フィルターパイプラインの最内部処理となる __Inner__ メソッドを生成
        // Generate the __Inner__ method that is the innermost delegate of the filter pipeline
        var methodName = handler.MethodName;
        builder.AppendLine($"private static async global::System.Threading.Tasks.ValueTask __{methodName}_Inner__(");
        builder.AppendLine($"    {InvocationContextType} ctx)");
        builder.BeginBlock();

        if (handler.Kind != HandlerKind.Event)
        {
            // HTTPリクエストをコンテキストから取り出してローカル変数に割り当て
            // Extract HTTP request from context and assign to local variable
            builder.AppendLine($"var request = ({V2RequestType})ctx.Request;");
            builder.NewLine();
        }
        else
        {
            // Get event type
            var eventParam = GetRequestParam(handler);
            if (eventParam != null)
            {
                builder.AppendLine($"var ev = ({eventParam.Type.FullName})ctx.Request;");
                builder.NewLine();
            }
        }

        BuildParameterBindings(builder, handler, hasFilter: true);

        BuildHandlerInvocation(builder, handler, hasFilter: true);

        builder.EndBlock();
    }

    private static void BuildPipeline(SourceBuilder builder, LambdaModel model, HandlerModel handler)
    {
        // フィルターを逆順にラップしてパイプラインデリゲートを構築し、静的フィールドに保持
        // Build the pipeline delegate by wrapping filters in reverse order and store as a static field
        var methodName = handler.MethodName;
        var pascal = ToPascalCase(methodName);
        builder.AppendLine($"private static readonly {FilterDelegateType} __{methodName}_Pipeline__ = Build{pascal}Pipeline();");
        builder.NewLine();
        builder.AppendLine($"private static {FilterDelegateType} Build{pascal}Pipeline()");
        builder.BeginBlock();

        var filters = model.Filters;
        // 最内部デリゲートから开始して外側に向かってフィルターを順次ラップ
        // Start from the innermost delegate and wrap each filter outward
        builder.AppendLine($"{FilterDelegateType} p = __{methodName}_Inner__;");
        builder.NewLine();

        for (var i = filters.Count - 1; i >= 0; i--)
        {
            var idx = filters[i].Index;
            builder.AppendLine($"var inner{i} = p;");
            builder.AppendLine($"p = ctx => __filter{idx}__.InvokeAsync(ctx, inner{i});");
            if (i > 0)
            {
                builder.NewLine();
            }
        }

        builder.NewLine();
        builder.AppendLine("return p;");
        builder.EndBlock();
    }

    private static void BuildHandlerMethod(SourceBuilder builder, LambdaModel model, HandlerModel handler)
    {
        // Lambda エントリポイントとなる public static メソッド (*_Handler) を生成
        // Generate the public static *_Handler method that serves as the Lambda entry point
        var methodName = handler.MethodName;
        var filters = model.Filters;
        var hasFilters = filters.Count > 0;

        // ハンドラー種別と戻り値型に応じた戻り値型文字列を決定
        // Determine the return type string based on handler kind and result type
        string returnType;
        if ((handler.Kind == HandlerKind.HttpApi) || (handler.Kind == HandlerKind.FunctionUrl) ||
            (handler.Kind == HandlerKind.HttpApiAuthorizer))
        {
            if (handler.ReturnsHttpResult || handler.Kind == HandlerKind.HttpApiAuthorizer)
            {
                returnType = $"global::System.Threading.Tasks.Task<{StreamType}>";
            }
            else
            {
                returnType = $"global::System.Threading.Tasks.Task<{V2ResponseType}>";
            }
        }
        else
        {
            if (handler.ResultType != null)
            {
                returnType = $"global::System.Threading.Tasks.Task<{handler.ResultType.FullName}>";
            }
            else
            {
                returnType = "global::System.Threading.Tasks.Task";
            }
        }

        builder.AppendLine($"public static async {returnType} {methodName}_Handler(");

        if (handler.Kind == HandlerKind.Event)
        {
            // Determine request param type
            var requestParam = GetRequestParam(handler);
            var reqTypeName = requestParam?.Type.FullName ?? V2RequestType;
            builder.AppendLine($"    {reqTypeName} ev,");
            builder.AppendLine($"    {LambdaContextType} context)");
        }
        else
        {
            builder.AppendLine($"    {V2RequestType} request,");
            builder.AppendLine($"    {LambdaContextType} context)");
        }

        builder.BeginBlock();

        if (hasFilters)
        {
            // フィルターあり: InvocationContext を作成しパイプラインを実行、結果を抽出
            // With filters: create InvocationContext, execute pipeline, then extract result
            builder.AppendLine($"var ctx = new {InvocationContextType}");
            builder.BeginBlock();

            if (handler.Kind == HandlerKind.Event)
            {
                builder.AppendLine("Request = ev,");
            }
            else
            {
                builder.AppendLine("Request = request,");
            }

            builder.AppendLine("LambdaContext = context,");
            builder.AppendLine("CancellationToken = default,");
            builder.EndBlock(semicolon: true);
            builder.NewLine();

            BuildTryCatchWithFilter(builder, handler);
        }
        else
        {
            // フィルターなし: パラメーターバインディングとハンドラー呼び出しを直接実行
            // Without filters: directly execute parameter binding and handler invocation
            if (handler.Kind == HandlerKind.Event)
            {
                BuildEventTryCatch(builder, handler);
            }
            else
            {
                BuildHttpTryCatch(builder, handler);
            }
        }

        builder.EndBlock();
    }

    private static void BuildTryCatchWithFilter(SourceBuilder builder, HandlerModel handler)
    {
        builder.AppendLine("try");
        builder.BeginBlock();
        builder.AppendLine($"await __{handler.MethodName}_Pipeline__(ctx);");
        builder.EndBlock();

        if (handler.Kind == HandlerKind.HttpApiAuthorizer)
        {
            builder.AppendLine("catch (global::System.Exception ex)");
            builder.BeginBlock();
            builder.AppendLine("context.Logger.LogLine(ex.ToString());");
            var format = handler.Authorizer?.EnableSimpleResponses == false
                ? $"{AuthorizerFormatType}.HttpApiIamPolicy"
                : $"{AuthorizerFormatType}.HttpApiSimple";
            builder.AppendLine($"return {AuthorizerResultsType}.Deny()");
            builder.AppendLine($"    .Serialize(new {AuthorizerResultOptionsType}");
            builder.BeginBlock();
            builder.AppendLine($"Format = {format},");
            builder.AppendLine("RouteArn = null");
            builder.EndBlock(semicolon: false);
            builder.AppendLine(");");
            builder.EndBlock();
        }
        else if ((handler.Kind == HandlerKind.HttpApi) || (handler.Kind == HandlerKind.FunctionUrl))
        {
            builder.AppendLine($"catch ({ApiExceptionType} ex)");
            builder.BeginBlock();
            if (handler.ReturnsHttpResult)
            {
                builder.AppendLine($"return {HttpResultsType}.NewResult((global::System.Net.HttpStatusCode)ex.StatusCode, ex.Message)");
                builder.AppendLine($"    .Serialize(new {HttpResultOptionsType} {{ Serializer = __lambdaSerializer__ }});");
            }
            else
            {
                builder.AppendLine($"return new {V2ResponseType} {{ StatusCode = (int)ex.StatusCode, Body = ex.Message }};");
            }
            builder.EndBlock();

            builder.AppendLine("catch (global::System.Exception ex)");
            builder.BeginBlock();
            builder.AppendLine("context.Logger.LogLine(ex.ToString());");
            if (handler.ReturnsHttpResult)
            {
                builder.AppendLine($"return {HttpResultsType}.InternalServerError()");
                builder.AppendLine($"    .Serialize(new {HttpResultOptionsType} {{ Serializer = __lambdaSerializer__ }});");
            }
            else
            {
                builder.AppendLine($"return new {V2ResponseType} {{ StatusCode = 500 }};");
            }
            builder.EndBlock();
        }
        else
        {
            builder.AppendLine("catch (global::System.Exception ex)");
            builder.BeginBlock();
            builder.AppendLine("context.Logger.LogLine(ex.ToString());");
            builder.AppendLine("throw;");
            builder.EndBlock();
        }

        builder.NewLine();
        BuildResultExtraction(builder, handler, hasFilter: true);
    }

    private static void BuildHttpTryCatch(SourceBuilder builder, HandlerModel handler)
    {
        builder.AppendLine("try");
        builder.BeginBlock();

        BuildParameterBindings(builder, handler, hasFilter: false);
        BuildHandlerInvocation(builder, handler, hasFilter: false);

        builder.EndBlock();

        if (handler.Kind == HandlerKind.HttpApiAuthorizer)
        {
            builder.AppendLine("catch (global::System.Exception ex)");
            builder.BeginBlock();
            builder.AppendLine("context.Logger.LogLine(ex.ToString());");
            var format = handler.Authorizer?.EnableSimpleResponses == false
                ? $"{AuthorizerFormatType}.HttpApiIamPolicy"
                : $"{AuthorizerFormatType}.HttpApiSimple";
            builder.AppendLine($"return {AuthorizerResultsType}.Deny()");
            builder.AppendLine($"    .Serialize(new {AuthorizerResultOptionsType}");
            builder.BeginBlock();
            builder.AppendLine($"Format = {format},");
            builder.AppendLine("RouteArn = null");
            builder.EndBlock(semicolon: false);
            builder.AppendLine(");");
            builder.EndBlock();
        }
        else
        {
            builder.AppendLine($"catch ({ApiExceptionType} ex)");
            builder.BeginBlock();
            if (handler.ReturnsHttpResult)
            {
                builder.AppendLine($"return {HttpResultsType}.NewResult((global::System.Net.HttpStatusCode)ex.StatusCode, ex.Message)");
                builder.AppendLine($"    .Serialize(new {HttpResultOptionsType} {{ Serializer = __lambdaSerializer__ }});");
            }
            else
            {
                builder.AppendLine($"return new {V2ResponseType} {{ StatusCode = (int)ex.StatusCode, Body = ex.Message }};");
            }
            builder.EndBlock();

            builder.AppendLine("catch (global::System.Exception ex)");
            builder.BeginBlock();
            builder.AppendLine("context.Logger.LogLine(ex.ToString());");
            if (handler.ReturnsHttpResult)
            {
                builder.AppendLine($"return {HttpResultsType}.InternalServerError()");
                builder.AppendLine($"    .Serialize(new {HttpResultOptionsType} {{ Serializer = __lambdaSerializer__ }});");
            }
            else
            {
                builder.AppendLine($"return new {V2ResponseType} {{ StatusCode = 500 }};");
            }
            builder.EndBlock();
        }
    }

    private static void BuildEventTryCatch(SourceBuilder builder, HandlerModel handler)
    {
        builder.AppendLine("try");
        builder.BeginBlock();

        BuildHandlerInvocationDirect(builder, handler);

        builder.EndBlock();
        builder.AppendLine("catch (global::System.Exception ex)");
        builder.BeginBlock();
        builder.AppendLine("context.Logger.LogLine(ex.ToString());");
        builder.AppendLine("throw;");
        builder.EndBlock();
    }

    private static void BuildParameterBindings(SourceBuilder builder, HandlerModel handler, bool hasFilter)
    {
        // 全パラメーターを順にバインディングコードを生成
        // Generate binding code for each parameter in order
        var parameters = handler.Parameters;
        for (var i = 0; i < parameters.Count; i++)
        {
            var p = parameters[i];
            BuildParameterBinding(builder, handler, p, i, hasFilter);
        }
    }

    private static void BuildParameterBinding(SourceBuilder builder, HandlerModel handler, ParameterModel param, int index, bool hasFilter)
    {
        var pVar = $"p{index}";
        var pRaw = $"p{index}raw";
        var requestVar = hasFilter ? "request" : "request";
        var typeName = param.Type.FullName;
        var key = param.Key;

        string BadRequest400(string paramName)
        {
            if (handler.ReturnsHttpResult)
            {
                return $"return {HttpResultsType}.BadRequest($\"Invalid parameter: {paramName}\")" +
                       $".Serialize(new {HttpResultOptionsType} {{ Serializer = __lambdaSerializer__ }});";
            }
            else
            {
                return $"return new {V2ResponseType} {{ StatusCode = 400, " +
                       $"Body = $\"Invalid parameter: {paramName}\" }};";
            }
        }

        switch (param.BindingKind)
        {
            case ParameterBindingKind.Request:
                // request/ev 変数はメソッド引数にそのまま存在するため何も不要
                // already in scope as 'request'
                return;

            case ParameterBindingKind.Context:
                // context 変数はメソッド引数にそのまま存在するため何も不要
                // already in scope as 'context'
                return;

            case ParameterBindingKind.FromServices:
                // DIコンテナからサービスを解決
                // Resolve service from DI container
                builder.AppendLine($"var {pVar} = {GetRequiredService}<{typeName}>(__provider__);");
                builder.NewLine();
                return;

            case ParameterBindingKind.FromBody:
                // リクエストボディをデシリアライズし、バリデーションを実行
                // Deserialize request body and run validation unless skipped
                builder.AppendLine($"var {pVar} = __bodySerializer__.Deserialize<{typeName}>({requestVar}.Body ?? string.Empty);");
                if (!param.SkipValidation)
                {
                    builder.AppendLine($"if ({pVar} is not null && !__requestValidator__.Validate({pVar}))");
                    builder.BeginBlock();
                    if (hasFilter)
                    {
                        builder.AppendLine($"ctx.Result = {HttpResultsType}.BadRequest(\"Validation failed: {param.Name}\");");
                        builder.AppendLine("return;");
                    }
                    else
                    {
                        builder.AppendLine($"{BadRequest400(param.Name)}");
                    }
                    builder.EndBlock();
                }
                builder.NewLine();
                return;

            case ParameterBindingKind.FromCustomAuthorizer:
                // Lambda オーソライザーが付与したカスタムコンテキストから値を取り出して変換
                // Extract and convert value from custom authorizer context injected by Lambda authorizer
                builder.AppendLine($"var {pVar} = default({typeName});");
                builder.AppendLine($"if ({requestVar}.RequestContext?.Authorizer?.Lambda is not null &&");
                builder.AppendLine($"    {requestVar}.RequestContext.Authorizer.Lambda.TryGetValue(\"{key}\", out var {pRaw}ca) &&");
                builder.AppendLine($"    {pRaw}ca is not null)");
                builder.BeginBlock();
                if (String.IsNullOrEmpty(param.ConverterMethod))
                {
                    builder.AppendLine($"{pVar} = {pRaw}ca as {typeName};");
                }
                else
                {
                    var isEnum = param.ConverterMethod == "TryToEnum";
                    var converterCall = isEnum
                        ? $"{StringConverterType}.TryToEnum<{GetBaseTypeName(param.Type)}>(({pRaw}ca as string ?? string.Empty).AsSpan(), out var {pVar}tmp)"
                        : $"{StringConverterType}.{param.ConverterMethod}(({pRaw}ca as string ?? string.Empty).AsSpan(), out var {pVar}tmp)";
                    builder.AppendLine($"if (!{converterCall})");
                    builder.BeginBlock();
                    if (hasFilter)
                    {
                        builder.AppendLine($"ctx.Result = {HttpResultsType}.BadRequest($\"Invalid parameter: {key}\");");
                        builder.AppendLine("return;");
                    }
                    else
                    {
                        builder.AppendLine(BadRequest400(key));
                    }
                    builder.EndBlock();
                    builder.AppendLine($"{pVar} = {pVar}tmp;");
                }
                builder.EndBlock();
                builder.NewLine();
                return;

            case ParameterBindingKind.FromRoute:
                // パスパラメーターディクショナリから値を取得して型変換
                // Retrieve and convert value from path parameters dictionary
                BuildScalarOrArrayBinding(
                    builder,
                    handler,
                    param,
                    index,
                    hasFilter,
                    $"{requestVar}.PathParameters");
                return;

            case ParameterBindingKind.FromQuery:
                // クエリストリングディクショナリから値を取得して型変換
                // Retrieve and convert value from query string parameters dictionary
                BuildScalarOrArrayBinding(
                    builder,
                    handler,
                    param,
                    index,
                    hasFilter,
                    $"{requestVar}.QueryStringParameters");
                return;

            case ParameterBindingKind.FromHeader:
                // リクエストヘッダーディクショナリから値を取得して型変換
                // Retrieve and convert value from request headers dictionary
                BuildScalarOrArrayBinding(
                    builder,
                    handler,
                    param,
                    index,
                    hasFilter,
                    $"{requestVar}.Headers");
                return;
        }
    }

    private static void BuildScalarOrArrayBinding(SourceBuilder builder, HandlerModel handler, ParameterModel param, int index, bool hasFilter, string dictExpr)
    {
        // 型に応じて 配列 / Nullable<T> / スカラー のバインディングコードを生成
        // Generate binding code for array, Nullable<T>, or scalar type accordingly
        var pVar = $"p{index}";
        var pRaw = $"p{index}raw";
        var typeName = param.Type.FullName;
        var key = param.Key;

        string Bad400()
        {
            if (handler.ReturnsHttpResult)
            {
                return $"return {HttpResultsType}.BadRequest($\"Invalid parameter: {key}\")" +
                       $".Serialize(new {HttpResultOptionsType} {{ Serializer = __lambdaSerializer__ }});";
            }
            else
            {
                return $"return new {V2ResponseType} {{ StatusCode = 400, Body = $\"Invalid parameter: {key}\" }};";
            }
        }

        if (param.Type.IsArray && param.Type.ElementType != null)
        {
            // カンマ分割で複数値を配列に変換、各要素を型変換
            // Split comma-separated values into array and convert each element
            var elemType = param.Type.ElementType.FullName;
            var converterMethod = param.ConverterMethod;
            builder.AppendLine($"var {pVar} = global::System.Array.Empty<{elemType}>();");
            builder.AppendLine($"if ({dictExpr} is not null &&");
            builder.AppendLine($"    {dictExpr}.TryGetValue(\"{key}\", out var {pRaw}) &&");
            builder.AppendLine($"    {pRaw} is not null)");
            builder.BeginBlock();
            builder.AppendLine($"var {pVar}parts = {pRaw}.Split(',');");
            builder.AppendLine($"{pVar} = new {elemType}[{pVar}parts.Length];");
            builder.AppendLine($"for (var i = 0; i < {pVar}parts.Length; i++)");
            builder.BeginBlock();
            if (String.IsNullOrEmpty(converterMethod))
            {
                builder.AppendLine($"{pVar}[i] = {pVar}parts[i];");
            }
            else
            {
                var isEnum = converterMethod == "TryToEnum";
                var converterCall = isEnum
                    ? $"!{StringConverterType}.TryToEnum<{elemType}>({pVar}parts[i].AsSpan(), out {pVar}[i])"
                    : $"!{StringConverterType}.{converterMethod}({pVar}parts[i].AsSpan(), out {pVar}[i])";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = {HttpResultsType}.BadRequest($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine(Bad400());
                }
                builder.EndBlock();
            }
            builder.EndBlock();
            builder.EndBlock();
            builder.NewLine();
        }
        else if (param.Type.IsNullable && param.Type.UnderlyingType != null)
        {
            // Nullable<T>: 値が存在する場合のみ型変換を実施
            // Nullable<T>: perform type conversion only when the value is present
            var baseType = param.Type.UnderlyingType.FullName;
            var converterMethod = param.ConverterMethod;
            builder.AppendLine($"var {pVar} = ({typeName})null;");
            builder.AppendLine($"if ({dictExpr} is not null &&");
            builder.AppendLine($"    {dictExpr}.TryGetValue(\"{key}\", out var {pRaw}) &&");
            builder.AppendLine($"    {pRaw} is not null)");
            builder.BeginBlock();
            if (String.IsNullOrEmpty(converterMethod))
            {
                builder.AppendLine($"{pVar} = {pRaw};");
            }
            else
            {
                var isEnum = converterMethod == "TryToEnum";
                var converterCall = isEnum
                    ? $"!{StringConverterType}.TryToEnum<{baseType}>({pRaw}.AsSpan(), out var {pVar}tmp)"
                    : $"!{StringConverterType}.{converterMethod}({pRaw}.AsSpan(), out var {pVar}tmp)";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = {HttpResultsType}.BadRequest($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine(Bad400());
                }
                builder.EndBlock();
                builder.AppendLine($"{pVar} = {pVar}tmp;");
            }
            builder.EndBlock();
            builder.NewLine();
        }
        else
        {
            // スカラー: string はそのまま取得、その他の型は StringConverter で変換
            // Scalar: take string as-is or convert other types via StringConverter
            var converterMethod = param.ConverterMethod;
            if (String.IsNullOrEmpty(converterMethod))
            {
                // string
                builder.AppendLine($"var {pVar} = default({typeName})!;");
                builder.AppendLine($"if ({dictExpr} is not null &&");
                builder.AppendLine($"    {dictExpr}.TryGetValue(\"{key}\", out var {pRaw}))");
                builder.BeginBlock();
                builder.AppendLine($"{pVar} = {pRaw};");
                builder.EndBlock();
                builder.NewLine();
            }
            else
            {
                builder.AppendLine($"var {pVar} = default({typeName});");
                builder.AppendLine($"if ({dictExpr} is not null &&");
                builder.AppendLine($"    {dictExpr}.TryGetValue(\"{key}\", out var {pRaw}) &&");
                builder.AppendLine($"    {pRaw} is not null)");
                builder.BeginBlock();
                var isEnum = converterMethod == "TryToEnum";
                var converterCall = isEnum
                    ? $"!{StringConverterType}.TryToEnum<{typeName}>({pRaw}.AsSpan(), out {pVar})"
                    : $"!{StringConverterType}.{converterMethod}({pRaw}.AsSpan(), out {pVar})";
                builder.AppendLine($"if ({converterCall})");
                builder.BeginBlock();
                if (hasFilter)
                {
                    builder.AppendLine($"ctx.Result = {HttpResultsType}.BadRequest($\"Invalid parameter: {key}\");");
                    builder.AppendLine("return;");
                }
                else
                {
                    builder.AppendLine(Bad400());
                }
                builder.EndBlock();
                builder.EndBlock();
                builder.NewLine();
            }
        }
    }

    private static void BuildHandlerInvocation(SourceBuilder builder, HandlerModel handler, bool hasFilter)
    {
        // 引数リストを組み立ててターゲットメソッドを呼び出し、結果をコンテキストまたは戻り値に設定
        // Build argument list, invoke target method, and assign result to context or return
        var args = BuildCallArgs(handler, hasFilter);
        var awaitPrefix = handler.IsAsync ? "await " : string.Empty;

        if (handler.Kind == HandlerKind.Event)
        {
            if (handler.ResultType != null)
            {
                builder.AppendLine($"var __result__ = {awaitPrefix}__target__.{handler.MethodName}({args});");
                if (hasFilter)
                {
                    builder.AppendLine("ctx.Result = __result__;");
                }
                else
                {
                    builder.AppendLine("return __result__;");
                }
            }
            else
            {
                builder.AppendLine($"{awaitPrefix}__target__.{handler.MethodName}({args});");
            }

            return;
        }

        builder.AppendLine($"var __result__ = {awaitPrefix}__target__.{handler.MethodName}({args});");

        if (hasFilter)
        {
            builder.AppendLine("ctx.Result = __result__;");
        }
        else
        {
            BuildResultExtraction(builder, handler, hasFilter: false);
        }
    }

    private static void BuildHandlerInvocationDirect(SourceBuilder builder, HandlerModel handler)
    {
        // フィルターなしのイベントハンドラー向け: 引数を直接指定してターゲットメソッドを呼び出す
        // For Event handler without filter: invoke target method with directly specified arguments
        // For Event handler without filter
        var awaitPrefix = handler.IsAsync ? "await " : string.Empty;
        var parameters = handler.Parameters;
        var argParts = new List<string>();

        for (var i = 0; i < parameters.Count; i++)
        {
            var p = parameters[i];
            switch (p.BindingKind)
            {
                case ParameterBindingKind.Request:
                    argParts.Add("ev");
                    break;
                case ParameterBindingKind.Context:
                    argParts.Add("context");
                    break;
                case ParameterBindingKind.FromServices:
                    argParts.Add($"p{i}");
                    break;
                default:
                    argParts.Add($"p{i}");
                    break;
            }
        }

        if (handler.ResultType != null)
        {
            builder.AppendLine($"var __result__ = {awaitPrefix}__target__.{handler.MethodName}({String.Join(", ", argParts)});");
        }
        else
        {
            builder.AppendLine($"{awaitPrefix}__target__.{handler.MethodName}({String.Join(", ", argParts)});");
        }
    }

    private static void BuildResultExtraction(SourceBuilder builder, HandlerModel handler, bool hasFilter)
    {
        // ハンドラー種別に応じて結果をシリアライズまたは変換して返値を生成
        // Serialize or convert the result according to handler kind and generate the return statement
        if (handler.Kind == HandlerKind.HttpApiAuthorizer)
        {
            var format = handler.Authorizer?.EnableSimpleResponses == false
                ? $"{AuthorizerFormatType}.HttpApiIamPolicy"
                : $"{AuthorizerFormatType}.HttpApiSimple";

            if (hasFilter)
            {
                builder.AppendLine($"var result = ({AuthorizerResultType})ctx.Result!;");
                builder.AppendLine($"return result.Serialize(new {AuthorizerResultOptionsType}");
                builder.BeginBlock();
                builder.AppendLine($"Format = {format},");
                builder.AppendLine("RouteArn = null");
                builder.EndBlock(semicolon: false);
                builder.AppendLine(");");
            }
            else
            {
                builder.AppendLine($"return __result__.Serialize(new {AuthorizerResultOptionsType}");
                builder.BeginBlock();
                builder.AppendLine($"Format = {format},");
                builder.AppendLine("RouteArn = null");
                builder.EndBlock(semicolon: false);
                builder.AppendLine(");");
            }
        }
        else if ((handler.Kind == HandlerKind.HttpApi) || (handler.Kind == HandlerKind.FunctionUrl))
        {
            if (handler.ReturnsHttpResult)
            {
                if (hasFilter)
                {
                    builder.AppendLine($"if (ctx.Result is {HttpResultType} httpResult)");
                    builder.BeginBlock();
                    builder.AppendLine($"return httpResult.Serialize(new {HttpResultOptionsType} {{ Serializer = __lambdaSerializer__ }});");
                    builder.EndBlock();
                    builder.NewLine();
                    builder.AppendLine($"return {HttpResultsType}.InternalServerError()");
                    builder.AppendLine($"    .Serialize(new {HttpResultOptionsType} {{ Serializer = __lambdaSerializer__ }});");
                }
                else
                {
                    builder.AppendLine($"return __result__.Serialize(new {HttpResultOptionsType} {{ Serializer = __lambdaSerializer__ }});");
                }
            }
            else
            {
                if (hasFilter)
                {
                    builder.AppendLine($"return ({V2ResponseType})ctx.Result!;");
                }
                else
                {
                    builder.AppendLine("return __result__;");
                }
            }
        }
    }

    private static string BuildCallArgs(HandlerModel handler, bool hasFilter)
    {
        // バインディング種別とフィルター有無に応じてハンドラー呼び出し用の引数文字列を構築
        // Build the argument string for the handler invocation based on binding kind and filter presence
        var parameters = handler.Parameters;
        var argParts = new List<string>();
        var isEvent = handler.Kind == HandlerKind.Event;

        for (var i = 0; i < parameters.Count; i++)
        {
            var p = parameters[i];
            switch (p.BindingKind)
            {
                case ParameterBindingKind.Request:
                    if (isEvent)
                    {
                        argParts.Add(hasFilter ? $"({p.Type.FullName})ctx.Request" : "ev");
                    }
                    else
                    {
                        argParts.Add(hasFilter ? "request" : "request");
                    }
                    break;
                case ParameterBindingKind.Context:
                    argParts.Add(hasFilter ? "ctx.LambdaContext" : "context");
                    break;
                default:
                    argParts.Add($"p{i}!");
                    break;
            }
        }

        return String.Join(", ", argParts);
    }

    private static ParameterModel? GetRequestParam(HandlerModel handler)
    {
        foreach (var p in handler.Parameters)
        {
            if (p.BindingKind == ParameterBindingKind.Request)
            {
                return p;
            }
        }
        return null;
    }

    private static string GetBaseTypeName(TypeRefModel type)
    {
        if (type.IsNullable && type.UnderlyingType != null)
        {
            return type.UnderlyingType.FullName;
        }

        if (type.IsArray && type.ElementType != null)
        {
            return type.ElementType.FullName;
        }

        return type.FullName;
    }

    private static string ToPascalCase(string name)
    {
        if (String.IsNullOrEmpty(name))
        {
            return name;
        }

        return char.ToUpperInvariant(name[0]) + name.Substring(1);
    }
}

internal static class SourceBuilderExtensions
{
    public static void AppendLine(this SourceBuilder builder, string line)
    {
        builder.Indent().Append(line).NewLine();
    }

    public static void BeginBlock(this SourceBuilder builder)
    {
        builder.Indent().Append("{").NewLine();
        builder.IndentLevel++;
    }

    public static void EndBlock(this SourceBuilder builder, bool semicolon = false)
    {
        builder.IndentLevel--;
        builder.Indent();
        if (semicolon)
        {
            builder.Append("};").NewLine();
        }
        else
        {
            builder.Append("}").NewLine();
        }
    }
}
