// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 17.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AmazonLambdaExtension.SourceGenerator.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using AmazonLambdaExtension.Helpers;
    using AmazonLambdaExtension.SourceGenerator.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class EventTemplate : EventTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 8 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"

    var contextIndex = handler.Parameters.FindIndex(x => x.Type.IsLambdaContext());
    var arguments = handler.Parameters
        .Select((x, i) => new { Parameter = x, Index = i })
        .Where(x => x.Parameter.ParameterType != ParameterType.FromServices)
        .Select(x => $"{x.Parameter.Type.FullName} p{x.Index}");
    if (contextIndex < 0)
    {
        arguments = arguments.Append($"Amazon.Lambda.Core.ILambdaContext p{handler.Parameters.Count}");
    }
    var artument = String.Join(", ", arguments);
    var contextArtument = contextIndex < 0 ? $"p{handler.Parameters.Count}" : $"p{contextIndex}";

            
            #line default
            #line hidden
            this.Write("#pragma warning disable CS8669\r\nnamespace ");
            
            #line 22 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(handler.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public sealed class ");
            
            #line 24 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(handler.WrapperClass));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n");
            
            #line 26 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 if (function.ServiceResolver != null) { 
            
            #line default
            #line hidden
            this.Write("        private readonly ");
            
            #line 27 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.ServiceResolver.FullName));
            
            #line default
            #line hidden
            this.Write(" serviceResolver;\r\n\r\n");
            
            #line 29 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 30 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 if (function.Filter != null) { 
            
            #line default
            #line hidden
            this.Write("        private readonly ");
            
            #line 31 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.Filter.Type.FullName));
            
            #line default
            #line hidden
            this.Write(" filter;\r\n\r\n");
            
            #line 33 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        private readonly ");
            
            #line 34 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.Function.FullName));
            
            #line default
            #line hidden
            this.Write(" function;\r\n\r\n        public ");
            
            #line 36 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(handler.WrapperClass));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n");
            
            #line 38 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 if (function.ServiceResolver != null) { 
            
            #line default
            #line hidden
            this.Write("            serviceResolver = new ");
            
            #line 39 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.ServiceResolver.FullName));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 40 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 41 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 if (function.Filter != null) { 
            
            #line default
            #line hidden
            this.Write("            filter = new ");
            
            #line 42 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.Filter.Type.FullName));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 43 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            function = new ");
            
            #line 44 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.Function.FullName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 44 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(",", function.ConstructorParameters.Select(x => $"serviceResolver.GetService<{x.FullName}>()"))));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n\r\n");
            
            #line 47 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 if (handler.IsAsync || function.IsAsyncRequired()) { 
            
            #line default
            #line hidden
            
            #line 48 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 if (handler.ResultType != null) { 
            
            #line default
            #line hidden
            this.Write("        public async System.Threading.Tasks.Task<");
            
            #line 49 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(handler.ResultType.FullName));
            
            #line default
            #line hidden
            this.Write("> Handle(");
            
            #line 49 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(artument));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 50 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("        public async System.Threading.Tasks.Task Handle(");
            
            #line 51 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(artument));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 52 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 53 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            
            #line 54 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 if (handler.ResultType != null) { 
            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 55 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(handler.ResultType.FullName));
            
            #line default
            #line hidden
            this.Write(" Handle(");
            
            #line 55 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(artument));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 56 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("        public void Handle(");
            
            #line 57 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(artument));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 58 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 59 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        {\r\n");
            
            #line 61 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 if (function.Filter?.Executing is not null) { 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 62 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.Filter.Executing.IsAsync ? "await " : ""));
            
            #line default
            #line hidden
            this.Write("filter.OnFunctionExecuting(");
            
            #line 62 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(contextArtument));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 62 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.Filter.Executing.IsAsync ? ".ConfigureAwait(false)" : ""));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 64 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            try\r\n            {\r\n");
            
            #line 67 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 for (var i = 0; i < handler.Parameters.Count; i++) { 
            
            #line default
            #line hidden
            
            #line 68 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 var parameter = handler.Parameters[i]; 
            
            #line default
            #line hidden
            
            #line 69 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 if (parameter.ParameterType == ParameterType.FromServices) { 
            
            #line default
            #line hidden
            this.Write("                var p");
            
            #line 70 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(" = serviceResolver.GetService<");
            
            #line 70 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type.FullName));
            
            #line default
            #line hidden
            this.Write(">();\r\n\r\n");
            
            #line 72 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 73 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 74 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(handler.ResultType != null ? "return " : ""));
            
            #line default
            #line hidden
            
            #line 74 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(handler.IsAsync ? "await " : ""));
            
            #line default
            #line hidden
            this.Write("function.");
            
            #line 74 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(handler.MethodName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 74 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ", handler.Parameters.Select((x, i) => $"p{i}"))));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 74 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(handler.IsAsync ? ".ConfigureAwait(false)" : ""));
            
            #line default
            #line hidden
            this.Write(";\r\n            }\r\n            catch (System.Exception ex)\r\n            {\r\n       " +
                    "         ");
            
            #line 78 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(contextArtument));
            
            #line default
            #line hidden
            this.Write(".Logger.LogLine(ex.ToString());\r\n                throw;\r\n            }\r\n");
            
            #line 81 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 if (function.Filter?.Executed is not null) { 
            
            #line default
            #line hidden
            this.Write("            finally\r\n            {\r\n                ");
            
            #line 84 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.Filter.Executed.IsAsync ? "await " : ""));
            
            #line default
            #line hidden
            this.Write("filter.OnFunctionExecuted(");
            
            #line 84 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(contextArtument));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 84 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function.Filter.Executed.IsAsync ? ".ConfigureAwait(false)" : ""));
            
            #line default
            #line hidden
            this.Write(";\r\n            }\r\n");
            
            #line 86 "D:\GitHubTemplate\amazon-lambda-extension\AmazonLambdaExtension.SourceGenerator\Templates\EventTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class EventTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
